---
sidebar: sidebar
permalink: support/get-help.html
keywords: how to get help with astra data store, how to get support with astra data store, astra data store knowledgebase, netapp technical support, slack, phone, web, ticket, contact support, support ticket, support bundle
summary: NetApp provides support for Astra Data Store in a variety of ways. Extensive free self-support options are available 24x7, such as knowledgebase (KB) articles and a Slack channel. Your Astra Data Store account includes remote technical support via web ticketing.
---

= Get help
:hardbreaks:
:icons: font
:imagesdir: ../media/support/

NetApp provides support for Astra Data Store in a variety of ways. Extensive free self-support options are available 24x7, such as knowledgebase (KB) articles and a Slack channel. Your Astra Data Store account includes remote technical support via web ticketing.

IMPORTANT: If you have an evaluation license for Astra Data Store, you can get technical support. However, case creation via NetApp Support Site (NSS) is not available. You can get in touch with Support via the feedback option or use the Slack channel for self service.

You must first link:../get-started/setup_overview.html[activate support for your NetApp serial number] in order to use these non self-service support options. A NetApp Support Site (NSS) SSO account is required for chat and web ticketing along with case management.

.Options
* <<Self-support options>>

== Self-support options

These options are available for free 24x7:

* https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra[Knowledge base (login required)^]
+
Search for articles, FAQs, or Break Fix information related to Astra Data Store.

* Documentation
+
This is the doc site that you're currently viewing.

* https://netapppub.slack.com/#astra[Slack^]
+
Go to the containers channel in thePub workspace to connect with peers and experts.

* Generate support bundles to provide to NetApp Support for troubleshooting

* Feedback email
+
Send an email to astra.feedback@netapp.com to let us know your thoughts, ideas, or concerns.

[discrete]
== Find more information
* https://kb.netapp.com/Advice_and_Troubleshooting/Miscellaneous/How_to_upload_a_file_to_NetApp[How to upload a file to NetApp (login required)^]
