sidebar:
  entries:
    - title: Astra Data Store docs
      url: /index.html
    - section: release-notes
    - section: concepts
    - section: get-started
    - section: use
    - section: rest-api
    - section: support
    - title: Legal notices
      url: /legal-notices.html

homepage:
  tiles:
    - title: Get started
      #image: ./media/outline_directions_run_black_18dp.png
      links:
        - title: Learn about Astra Data Store
          url: /concepts/intro.html
        - title: What's in Astra Data Store
          url: /release-notes/whats-new.html
        - title: Release notes
          url: /release-notes/rn_overview.html
        - title: Try it out
          url: /get-started/setup_overview.html#add-a-license-for-astra-control-center
        - title: Install Astra Data Store
          url: /get-started/install_acc.html
    - title: Use Astra Data Store
      links:
        - title: Manage accounts
          url: /use/manage-users.html
        - title: Manage apps
          url: /use/manage-apps.html
        - title: Protect apps
          url: /use/protect-apps.html
        - title: Clone and migrate apps
          url: /use/clone-apps.html
    - title: Use Astra API
      links:
        - title: Get started with the Astra API
          url: https://docs.netapp.com/us-en/astra-automation/get-started/before_get_started.html
        - title: API reference
          url: https://docs.netapp.com/us-en/astra-automation/reference/api_reference.html
        - title: API workflows
          url: https://docs.netapp.com/us-en/astra-automation/workflows/workflows_before.html
    - title: Solution briefs
      links:
        - title: PostgreSQL DBaaS with Astra Control
          url: https://cloud.netapp.com/hubfs/SB-4122-0221-PostgresSQL-DBaaS-with-Astra%20(2).pdf
        - title: MySQL DBaaS with Astra Control
          url: https://cloud.netapp.com/hubfs/SB-4110-0221-MySQL-Astra%20(2).pdf
        - title: Simplify Jenkins lifecycle management
          url: https://cloud.netapp.com/hubfs/SB-4100-Jenkins%20(2).pdf
    - title: Demos & tutorials
      links:
        - title: Deploy Jenkins
          url: /solutions/jenkins-deploy-from-helm-chart.html
        - title: Deploy MariaDB
          url: /solutions/mariadb-deploy-from-helm-chart.html
        - title: Deploy MySQL
          url: /solutions/mysql-deploy-from-helm-chart.html
        - title: Deploy Postgres
          url: /solutions/postgres-deploy-from-helm-chart.html
    - title: Blogs & community
      links:
        - title: Slack channel
          url: https://netapppub.slack.com/#astra
        - title: NetApp Community
          url: https://community.netapp.com/
        - title: Kubernetes Hub
          url: https://cloud.netapp.com/kubernetes-hub
        - title: Where to get help
          url: /support/get-help.html
