---
sidebar: sidebar
permalink: use/configure-endpoints.html
keywords: astra, astra data store, kubectl, endpoints, confluent
summary: You can use kubectl commands with Astra Data Store to configure endpoints for use with Confluent, for example.
---

= Configure and monitor event logs
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/


To monitor Event Management System (EMS) logs, you can do the following high level tasks:

* <<Configure monitoring in the Astra Data Store cluster custom resource (CR)>>
* <<Set up Fluentd to stream logs to Cloud Insights>>
* <<Stream event logs to Elastic>>.

== Configure monitoring in the Astra Data Store cluster custom resource (CR)

If the monitoring option has not been configured the Astra Data Store cluster CR, you can set it up using `astrads` extensions.

====
kubectl astrads monitoring setup -m <NAMESPACE OF AGENT INSTALLED>  -r <DOCKER REPO TO FIND FLUENT/TELEGRAF ETC IMAGES>
====


== Set up Cloud Insights

See link:../use/monitor-with-cloud-insights.html[how to set up NetApp Cloud Insights] for use with Astra Data Store.


== Set up Fluentd to stream logs to Cloud Insights

To stream Fluentd logs to Cloud Insights, use the following kubectl command to set it up.

You can send logs (Kubernetes events) from Astra Data Store to your Fluentd endpoint. The Fluentd connection is disabled by default.

NOTE: Only the event logs from managed clusters are forwarded to Fluentd.

====
kubectl astrads monitoring ci --domain <CI_DOMAIN> --apiKey <CI_API_KEY> --fluent
====


Now you can visit the Fluentd server that you connected and view the event logs.

If the connection failed for some reason, the status shows Failed.

NOTE:	If you are having trouble with log collection, you should log in to your worker node and ensure that your logs are available in /var/log/containers/.

== Stream event logs to Elastic
To stream EMS events and other pod logs to streams logs to a third-party endpoint such as Elastic, use the `astrads` extensions.

====
kubectl astrads monitoring --host <ELASTIC HOST NAME> --port <ELASTIC HOST PORT> es
====
