---
sidebar: sidebar
permalink: use/kubectl-commands-ads.html
keywords: astra, astra data store, astra datastore, kubectl
summary: You can use kubectl commands directly with Astra Data Store.
---

= Use kubectl commands with Astra Data Store
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

You can use kubectl commands directly with Astra Data Store.

These instructions show you how to use Astra Data Store using a sample MongoDB app and YSCB IO Tool workflow. The application workload structure includes one MongoDB deployment consisting of a replica-set, which creates a mongo pod and with a MongoDB container running inside that pod.

The deployment references a Trident persistent volume claim (PVC). This PVC initializes its own PV: `astradsvolume` and `astradsexportpolicy`. When the YSCB tool is started, IO is sent to the Mongo container inside the pod, and the mounted `astradsvolume` is filled with data.

While all artifacts in these instructions exist in the same namespaces (for example: `astrads-system`), you can instead have their internal namespaces assigned to separate apps from backend artifacts.

== Some tasks you can do with kubectl commands

You can perform many Astra Data Store tasks with kubectl commands.

Here are instructions for some of them:

* <<Place a node in maintenance mode>>
* <<Describe the deployment>>
* <<Display volumes>>
* <<Display the server IP>>
* <<Describe the volume>>
* <<Show the volume mount on a node>>
* <<Show the volume mount inside a MongoDB container>>
* <<Replace a drive>>
* <<Replace a node>>


== Available commands

* *asup*: Manage AutoSupport.
* *clusters*: Display a cluster.
* *drives*: List drives in a cluster – just lists drives
* *faileddrive*: Replace a failed drive in a cluster.
* *help*: Get help about any command.
* *license*: Add a license in the astrads cluster, during the initial Astra Data Store deployment or if you need to update a license after deployment.
* *maintenance*: Place a node into maintenance mode.
* *monitoring*: Manage monitoring output by deploying the monitoring operator. This is done during the initial Astra Data Store deployment.
+
See link:../get-started/install-ads.html#install-the-monitoring-operator[Configure Astra Data Store for monitoring].
* *nodes*: List the nodes in a cluster.

== Place a node in maintenance mode

TBD

== Describe the deployment

Enter: `kubectl describe deployment -n astrads-system mongo0`

Response:

====
Pod template:
  Labels: app=mongo0
          ...
          role=database
  Containers:
    mongo0:
      Image: mongo0
      Post: 27017/TCP
      Host Port:
      Command:
        Mongod
         --bind_ip_all
      Environment: <none>
      Mounts:
        /data/db from target10 (rw)
  Volumes:
    target10:
      Type:
      ClaimName: mongo-pvc0
      ReadOnly: false
====

== Display volumes

Display the volumes to which it is bound.

Enter: `kubectl describe pvc -n astrads-system mongo0`

Response:
====
Name:         mongo-pvc0
Namespace:    astrads-system
StorageClass: trident-csi
Status:       Bound
Volume:
====

== Display the server IP

Enter: `kubectl get astradsvolumes -n astrads-system | grep <volume_ID>``

Response:

====
<volume_ID> 8Gi astrads-cluster-420a40  true
====



== Describe the volume

Enter: `kubectl describe astradsvolumes -n astrads-system <volume_ID>``

Response:

====
Spec:
  Cluster:
  Display Name:
  Export Policy:
  No Snap Dir: true
  Permissions:
  QoS Policy: Read/Write
  Volume Path:
Status:
  Cluster:
  Conditions:
    Last Transmission Time:
    Message:
    Reason: VolumeOnline
    Status: True
    Type: AstraDSVolumeOnline
====

== Show the volume mount on a node

. Enter: `kubectl get pods -n astrads-system`

+
Response:
+
====
mongo00  1/1 Running 0   23m
mongo01  1/1 Running 0   21m
====

. Enter: `kubectl describe pod -n astrads-system mongo0  | grep Node`

+
Response:
+
====
Node:
Node-Selectors: <none>
====

. Enter: `ssh <IP-address> -l root`
. Enter: `mount | grep pvc`

== Show the volume mount inside a MongoDB container

. Enter: `kubectl get pods -n astrads-system`

+
Response:
+
====
mongo0  1/1 Running 0   23m
mongo1  1/1 Running 0   21m
====

. Enter: `kubectl exec -it -n astrads-system mongo0 <pod_id>`
. Log into MongoDB.
. Enter: `show dbs`
. Enter: `use ycsb-_rand0_`
. Enter: `show collections`

== Replace a drive

== Replace a node
