---
sidebar: sidebar
permalink: use/kubectl-commands-ads.html
keywords: astra, astra data store, astra datastore, kubectl
summary: You can use kubectl commands directly with Astra Data Store.
---

= Manage Astra Data Store with kubectl commands or the Astra Data Store API extension
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

You can manage Astra Data Store assets by using kubectl commands or the Astra Data Store API extension.

These instructions show you how to manage Astra Data Store assets by using a sample MongoDB app and Yahoo Cloud Serving Benchmark (YSCB) IO tool workflow. The sample app provides context for the examples. The application workload structure includes one MongoDB deployment consisting of a replica-set, which creates a mongo pod and with a MongoDB container running inside that pod.


For the following cluster maintenance information, see link:../use/maintain-cluster.html[Manage the cluster]:

* Place a node in maintenance mode
* Replace a drive
* Add a node
* Replace a node


== Available commands

* *asup*: Manage AutoSupport.
* *clusters*: Display a cluster.
* *drives*: List drives in a cluster.
* *faileddrive*: Replace a failed drive in a cluster.
* *help*: Get help about any command.
* *license*: Add a license in the astrads cluster, during the initial Astra Data Store deployment or if you need to update a license after deployment.
* *maintenance*: Place a node into maintenance mode.
* *monitoring*: Manage monitoring output by deploying the monitoring operator. This is done during the initial Astra Data Store deployment.
+
See link:../get-started/install-ads.html#install-the-monitoring-operator[Configure Astra Data Store for monitoring].
* *nodes*: List the nodes in a cluster.

== List of Astra Data Store kubernetes custom API resources
You can use kubectl commands to display a list of Astra Data Store custom API resources.

----
 kubectl api-resources --api-group astrads.netapp.io
NAME                   SHORTNAMES  APIGROUP           NAMESPACED  KIND
astradsversions         adsve      astrads.netapp.io  true        AstraDSVersion
astradsclusters         adscl      astrads.netapp.io  true        AstraDSCluster
astradslicenses         adsli      astrads.netapp.io  true        AstraDSLicense
astradsnodeinfoes       adsni      astrads.netapp.io  true        AstraDSNodeInfo
astradsvolumes          adsvo      astrads.netapp.io  true        AstraDSVolume
astradsqospolicies      adsqp      astrads.netapp.io  true        AstraDSQosPolicy
astradsexportpolicies   adsep      astrads.netapp.io  true        AstraDSExportPolicy
astradsvolumesnapshots  adsvs      astrads.netapp.io  true        AstraDSVolumeSnapshot
astradsvolumefiles      adsvf      astrads.netapp.io  true        AstraDSVolumeFiles
astradsautosupports     adsas      astrads.netapp.io  true        AstraDSAutoSupport
astradsfaileddrives     adsfd      astrads.netapp.io  true        AstraDSFailedDrive
astradsnodemanagements  adsnm      astrads.netapp.io  true        AstraDSNodeManagement
----



== Describe the volume

Enter: `kubectl describe astradsvolumes -n astrads-system <volume_ID>``

Response:

----
 Spec:
  Cluster:
  Display Name:
  Export Policy:
  No Snap Dir: true
  Permissions:
  QoS Policy: Read/Write
  Volume Path:
Status:
  Cluster:
  Conditions:
    Last Transmission Time:
    Message:
    Reason: VolumeOnline
    Status: True
    Type: AstraDSVolumeOnline
----
