---
sidebar: sidebar
permalink: use/manage-keys.html
keywords: astra, astra data store, kubectl, security, secure, expired, key, ekm, encryption, sear
summary: You can manually revoke compromised or expired certificates in Astra Data Store.
---

= Manage external keys

You can use one or more external key management servers to secure the keys that the cluster uses to access encrypted data. An external key management server is a third-party system in your storage environment that serves keys to nodes using the Key Management Interoperability Protocol (KMIP).


Astra Data Store supports Software Encryption at Rest (SEAR) by default on the Astra Data Store cluster.

Managing keys involves the following custom resource definitions (CRDs):

* *AstraDSKeyProvider*: Configures an external KMIP server, which could be a cluster of servers
* *AstraDSSEARKeyRotate*: Gets a new key encryption key from the key provider and provides it to Astra Data Store.

You can perform the following tasks related to external key management:

* <<Set up external key management>>
* <<Change external to internal key management>>
* <<Rotate keys for security>>



== Set up external key management

Setting up external key management in Astra Data Store uses `kubectl astrads` commands.

.What you'll need

You will need an SSL certificate on the cluster or KMIP server that enables you to set up external keys, for example, by using OpenSSL.

.Steps
. Prepare the certificate for the key provider client. Include the client certificate, client private key, and trust CA bundles.
+
NOTE: You'll prepare the SSL certificate on the cluster or KMIP server that allows you to set up external keys, for example, by using OpenSSL.

. Log in to one of the nodes in the Astra Data Store cluster.

. Configure the key provider for the Astra Data Store cluster by entering the following kubectl extension CR:
+
----
kubectl-astrads key-provider certs --key key.pem
--client-cert client_cert.pem --ca-cert server_ca.pem
--hostnames=<kmip_server_ip> <key_provider_cr_name>
--namespace astrads-system --cluster <ads_cluster_name>
----



== Change external to internal key management

If you are currently using an external key manager, you can change it to an internal key manager.

.Steps

. Change the AstraDSCluster CR by removing the SoftwareEncryptionAtRest configuration.

. (Optional) Delete the previous AstraDSKeyProvider and associated secret.

NOTE: The previous key provider and secret will not be automatically removed.



== Rotate keys for security

Key rotation enhances security. By default, Astra Data Store rotates keys automatically every 90 days. You can change the default setting. Additionally, you can rotate keys on demand when you want.


.Configure automatic key rotation

. Update the AstraDSSEARKeyRotate parameter in the CRD. 


.Configure on-demand key rotation

. Create an ASTRADSEARKeyRotateRequest CR to rotate keys.
