---
sidebar: sidebar
permalink: use/monitor-with-prometheus-grafana.html
keywords: astra, astra data store, kubectl, endpoints, prometheus, grafana, visualization
summary: You can monitor Astra Data Store assets using Prometheus and Grafana.
---

= Monitor metrics with Prometheus and Grafana
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

You can monitor Astra Data Store preview metrics with Grafana and Prometheus. You can configure Prometheus to gather metrics from the Astra Data Store metrics endpoint, and you can use Grafana to visualize the metrics data.

.What you'll need
Make sure that you have downloaded and installed the Prometheus and Grafana packages on the Astra Data Store cluster.


== Configure Prometheus
Astra Data Store preview exposes a metrics service on TCP port 9341. You need to configure Prometheus to collect metrics from this service.

. Log in to the Astra Data Store preview cluster.
. Edit the `/usr/local/etc/prometheus.yml` file.
. Add a service target that points to the Astra Data Store preview service name and its port. For example:
+
----
scrape_configs:
static_configs:
- targets: ['astrads-metrics-service.astrads-system:9341']
----
. Start the Prometheus service.


== Configure Grafana
You can configure Grafana to display the metrics collected by Prometheus.

. Log in to the Astra Data Store preview cluster.
. Edit the Grafana configuration file `datasources.yaml`.
. Add Prometheus as a data source. For example:
+
----
apiVersion: 1

datasources:
  - name: astradatastore-prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    jsonData:
      manageAlerts: false
----
. Start the Grafana service.
. Follow the instructions in the Grafana documentation to https://grafana.com/docs/grafana/latest/getting-started/getting-started/[get started^].
