---
sidebar: sidebar
permalink: use/monitor-with-cloud-insights.html
keywords: astra, astra data store, kubectl, endpoints, cloud insights
summary: You can use kubectl commands with Astra Data Store to configure endpoints for use with Confluent, for example.
---

= Monitor resources with Cloud Insights
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

You can monitor Astra Data Store assets using Cloud Insights metrics.

* <<Perform Cloud Insight connection prerequisites>>
* <<Retrieve the Cloud Insights API Key>>
* <<Install the Astra Data Store Monitoring Operator>>
* <<Install the Astra Data Store collector>>

== Perform Cloud Insight connection prerequisites

Prior to connecting Astra Data Store with Cloud Insights, you need to:

* link:install-ads.html#install-the-monitoring-operator[Install the Astra Data Store Monitoring Operator].
* link:install-ads.html#copy-the-binary-and-push-images-to-your-local-registry[Install the kubectl-astrads binary] by following the Astra Data Store installation documentation.
* Ensure that the following commands are available: `awk, curl, grep` and `jq`

Gather the following information:

* *Cloud Insights API Key* with Read/Write permissions to the categories: Acquisition Unit, Data Collection, Data Ingestion and Log Ingestion. This will be used for the read/write operations, setting up the Acquisition Unit and setting up data ingest processes.
* *Kubernetes API Server IP address and port*. This is used to monitor the Astra Data Store cluster.
* *Kubernetes API Token*. This is used to call Kubernetes APIs.
* *Persistent volume information*. Information about the persistent volumes that are already created.

== Download and run the installation script

Cloud Insights provides a Bash script to enable Astra Data Store monitoring via the Monitoring Operator. The install script will install an Acquisition Unit with the Astra Data Store collector, a Telegraf Agent, and a Fluent Bit Agent.

The Cloud Insights tenant domain name and selected API Access Key will be embedded in the installer script when it is downloaded.

Then, metrics will be sent as follows:

* Telegraf will send metrics to the Cloud Insights data lake.
* Fluent Bit will send logs to the log ingestion service.

.Steps
. From the Cloud Insights menu, click on *Admin* > *Data Collectors*.
. Click on *+ Data Collector* to add a new collector.
. Click on the *Astra Data Store* tile.
. Select the correct API Access Token or create a new one.
. Follow the instructions to download the installer script, update the permissions, and run the script.
+
The script contains your Cloud Insights tenant URL and the selected API Access Token.

. Click *Complete Setup* after the script completes.
+
The Astra Data Store collector appears in the Datasources list.
+
NOTE: If the script exits due to an error, you can rerun it again once the error is resolved. The script supports additional parameters such as the Monitoring Operator namespace and Kubernetes API server port if your environment does not use the default settings. Use the ``"-h"`` option to see the usage and help text.

+
Running the installation script produces output that looks like:
+
====
 Configuring Cloud Insights monitoring for Astra Data Store . . .
Configuring monitoring namespace
...
Configuring output sink and Fluent Bit plugins
Configuring Telegraf plugins
Configuring Acquisition Unit
...
Acquisition Unit has been installed successfully.
Configuring Astra Data Store data collector
Astra Data Store collector data '<CLUSTER_NAME>' created
Configuration done!
====
+
The Monitoring Operator now installs the Acquisition Unit, Telegraf agent and Fluent Bit agent. This might take several minutes to complete.

. Periodically check the Acquisition Unit status until the status is `UP`. Alternatively, you can wait for the new Acquisition Unit to appear in the Cloud Insights UI under the Acquisition Units tab of the Data Collectors page (*Admin* > *Data Collectors*).
+
====
kubectl --namespace netapp-monitoring get agent -o jsonpath='{.status.au-pod-status}' agent-monitoring-netapp
====


=== Acquisition Unit storage
The Acquisition Unit requires three Persistent Volumes for storing installation files, configuration data and logs. The Monitoring Operator uses the default storage class to create Persistent Volume Claims. You can specify a different storage class name using the ``-s` option when running the installer script.

If your Kubernetes cluster does not have a storage provisioner (such as NetApp Trident), you can provide a local filesystem path using the `-r` option when running the installer script. When the `-r` option is set, the installer script creates three persistent volumes inside the provided directory. This directory requires a minimum of 150 GB free space.


=== Installer script help

The full help text for the installer script is shown below:

====
 $ ./cloudinsights-ads-monitoring.sh -h
USAGE: cloudinsights-ads-monitoring.sh [OPTIONS]
Configure monitoring of Astra Data Store by Cloud Insights.
OPTIONS:
  -h                      Display this help message.
  -d ci_domain_name       Cloud Insights tenant domain name.
  -i kubernetes_ip        Kubernetes API server IP address.
  -k ci_api_key           Cloud Insights API Access Key.
  -n namespace            Namespace for monitoring components. (default: netapp-monitoring)
  -p kubernetes_port      Kubernetes API server port. (default: 6443)
  -r root_pv_dir          Create 3 Persistent Volumes in this directory for the Acquisition Unit.
                          Only specify this option if there is no Storage Provisioner installed and the PVs do not already exist.
  -s storage_class        Storage Class name for provisioning Acquisition Unit PVs. If not specified, the default storage class will be used.
  -t kubernetes_token     Kubernetes API server token.
====


=== Edit the Cloud Insights connection
You can later edit the Kubernetes API key or the Cloud Insights API key:

* If you want to update Kubernetes API key, you should edit the Astra Data Store collector from the Cloud Insights UI.
* If you want to update the Cloud Insights API Keys used for telemetry and logs, you should edit the Monitoring Operator CR using kubectl commands.


==== Update the Kubernetes API token
. Log in to Cloud Insights.
. Select *Admin* > *Data Collectors* to access the Data Collectors page.
. Find the entry for the Astra Data Store cluster.
. Click on the menu on the right side of the page, and select *Edit*.


==== Update the Cloud Insights API access token
Repeat the steps in the previous section to create a new Cloud Insights API key.

. Log in to Cloud Insights.
. Access the API by selecting *Admin* > *API Access*.
. Edit the Agent CR:
+
====
kubectl --namespace netapp-monitoring edit agent agent-monitoring-netapp
====

. Locate the `output-sink` section and find the entry with the name ``"CI"``.
. For the label `api-key`, replace the current value with the new API Key.
+
The section looks something like this:
+
====
 output-sink:
  - api-key: <api key value>
    domain-name: <tenant url>
    name: CI
====

. Save and quit the editor window.

The Monitoring Operator will update Telegraf and Fluent Bit to use the new API Key.

=== Disconnect from Cloud Insights
To disconnect from Cloud Insights, you will need to delete the Astra Data Store collector from the Cloud Insights UI first. After that is complete, you can remove the Acquisition Unit, Telegraf and Fluent Bit configurations from the Monitoring Operator.

==== Remove the Astra Data Store collector
To disconnect from Cloud Insights, you must delete the Astra Data Store collector from the Cloud Insights UI first. After that is complete, you can remove the Acquisition Unit, Telegraf and Fluent Bit configurations from the Monitoring Operator.

.Steps
. Log in to Cloud Insights.
. Select *Admin* > *Data Collectors* to access the Data Collectors page.

. Find the entry for the Astra Data Store cluster.
. Select the kebab menu on the right side of the screen, and select *Delete*.
. Click *Delete* on the confirmation page.

==== Remove the Acquisition Unit, Telegraf and Fluent Bit

. Edit the Agent CR:
+
====
kubectl --namespace netapp-monitoring edit agent agent-monitoring-netapp
====

. Locate the `au`  section and set `isEnabled: false`
. Locate the `fluent-bit` section and remove the plugin named ``"ads-tail-ci"``. If there are no more plugins, you can remove the `fluent-bit` section.
. Locate the `telegraf`  section and remove the plugin named ``"ads-open-metric"``. If there are no more plugins, you can remove the `telegraf` section.

. Locate the `output-sink` section and remove the sink named ``"CI"``.
. Save and quit the editor window.

The Monitoring Operator will update the Telegraf and Fluent Bit configurations and remove the Acquisition Unit.
