---
sidebar: sidebar
permalink: get-started/faq-ads.html
keywords: faq, frequently asked questions, astra, astra data store, kubernetes, persistent volumes
summary: This FAQ can help if you're just looking for a quick answer to a question.
---

= Frequently asked questions for Astra Data Store
:hardbreaks:
:icons: font
:imagesdir: ../media/

This FAQ can help if you're just looking for a quick answer to a question.

For additional clarifications, please reach out to astra.feedback@netapp.com

== Licensing

*Does the Astra Data Store preview require a license?*

Yes, Astra Data Store preview requires a NetApp license file (NLF).

See link:../get-started/requirements.html#licensing[learn about Astra Data Store requirements].

== Support

*What type of support is included with the Astra Data Store preview?*

With the Astra Data Store preview, you can access community only support using the Container Slack channel. This channel is monitored by NetApp Support and our Technical Marketing Engineers.

https://netapp.io/slack[NetApp Container Slack channel]

The preview release requires that your system is connected to the cloud and integrated into the NetApp Active IQ and AutoSupport tools.

This is the only Support offered with the preview release.

See link:../support/get-help-ads.html[learn about Astra Data Store support operations].

== Cluster management

*Will NetApp Trident be uninstalled if I remove a Kubernetes cluster from Astra Data Store?*

Trident will not be uninstalled from a cluster if you remove it from Astra Data Store.
