---
sidebar: sidebar
permalink: get-started/faq-ads.html
keywords: faq, frequently asked questions, astra, astra data store, kubernetes, persistent volumes
summary: This FAQ can help if you're just looking for a quick answer to a question.
---

= Frequently asked questions for Astra Data Store
:hardbreaks:
:icons: font
:imagesdir: ../media/

Find answers to the frequently asked questions about installing, configuring, upgrading, and troubleshooting Astra Data Store Early Access Program release.


== General questions

*Can I use the Astra Data Store Early Access Program release for production?*
No. While Astra Data Store is designed and developed to deliver enterprise grade resiliency, the Early Access Program release of Astra Data Store is not targeted for production workloads.

*Can I use Astra Data Store for virtual machine workloads?*
//Astra Data Store release is limited only to applications running on Kubernetes, whether on bare metal or virtual machines. Future releases will support applications on both Kubernetes and directly on ESXi virtual machines.
Yes. Astra Data Store supports both Kubernetes and VMware vVol workloads.

See link:../use-vmware/use-ads-vmware-overview.html[Learn about Astra Data Store with VMware].

*Can I use VMware vSphere to manage Astra Data Store?*
Yes, Astra Data Store can be natively managed in vCenter with the NetApp Astra Plugin for VMware vSphere.
See link:../use-vmware/manage-ads-vmware.html[Manage Astra Data Store components of your VMware installation].

*Does Astra Data Store have any dependencies on other NetApp products for its functioning?*

Yes. Astra Data Store requires NetApp CSI driver Astra Trident version 21.10.1 and later to be deployed on workload Kubernetes clusters. Learn about link:../get-started/requirements.html[Astra Data Store requirements].

Astra Control Center is required to enable the VMware workflows and NetApp Astra Plugin for VMware vSphere.

Applications using an Astra Data Store cluster as a storage backend can use https://docs.netapp.com/us-en/astra-control-center/index.html[Astra Control Center^] to leverage application-aware data management capabilities, including data protection, disaster recovery, and migration of Kubernetes workloads.

*How can I manage the Astra Data Store cluster?*
You can manage Astra Data Store resources by using kubectl commands and by using the Kubernetes API extension.

The `kubectl astrads` command includes an `-h` switch that provides usage and flag documentation for your convenience.

*How can I monitor Astra Data Store cluster metrics?*
You can monitor Astra Data Store metrics using Cloud Insights (see link:../use/monitor-with-cloud-insights.html[Monitor metrics with Cloud Insights]) or Kubernetes native monitoring (see link:../use/monitor-with-prometheus-grafana.html[Monitor with Prometheus and Grafana]).

You can also monitor logs. See link:../use/configure-endpoints.html[Configure and monitor event logs].

*Can I use Astra Data Store along with ONTAP or other storage providers in my Kubernetes clusters?*
Yes. Astra Data Store can be used along with other storage providers in your application clusters.

*Will Astra Trident be uninstalled if I remove a Kubernetes cluster from Astra Data Store?*
Astra Trident will not be uninstalled from the cluster if you uninstall Astra Data Store. If you require Astra Trident to be uninstalled, you will have to do it separately.

== Licensing

*Does Astra Data Store require a license?*
Yes, Astra Data Store requires an evaluation NetApp license file (NLF).
//The Astra Data Store preview release also requires a NetApp license file (NLF).

See link:../get-started/requirements.html[Astra Data Store requirements].

*How long is the Astra Data Store evaluation license valid?*
The Astra Data Store license has a default term of 90 days from the download date.


== Installation and use of Astra Data Store on a Kubernetes cluster

*Can I install Astra Data Store on a Kubernetes cluster running on bare metal or virtual machines?*
Yes. Astra Data Store can be installed on a Kubernetes cluster running on bare metal or on vSphere VMs. See link:../get-started/requirements.html[Astra Data Store requirements].

*What are the supported versions of Kubernetes for Astra Data Store?*

Astra Data Store works with Kubernetes distributions that are compatible with v1.20 and later. However, it is not currently validated with all Kubernetes distributions. Learn about link:../get-started/requirements.html[Astra Data Store requirements].

*My Kubernetes cluster is larger than 4 worker nodes. Can I install Astra Data Store on it?*
Yes. An Astra Data Store cluster must be initially deployed on 4 worker nodes in a Kubernetes cluster. After deployment, you can grow the cluster up to a maximum of 16 worker nodes.

*Does Astra Data Store support an offline installation from a private registry?*
Yes. Astra Data Store can be installed offline from a local registry. See link:../get-started/install-ads.html[Install Astra Data Store].

*Do I need internet connectivity to use Astra Data Store?*
No, Astra Data Store Early Access Program does not require internet connectivity. However, it is recommended to have connectivity to the NetApp AutoSupport backend periodically to send the mandatory telemetry AutoSupport bundles. This connectivity can be direct or via a proxy.

*What are the roles and privileges used by Astra Data Store?*
You need to be a kube admin to deploy the Astra Data Store operator.

Astra Data Store has a privileged daemonset called `astrads-ds-nodeinfo` for discovering node resources used in selecting nodes.

In addition, the operator will use privileged Kubernetes jobs to install the storage cluster’s containers on the selected worker nodes to build the Astra Data Store storage cluster.

*What manifest files do I need to update for Astra Data Store installation?*
From the Astra Data Store bundle you download from the https://mysupport.netapp.com/site/products/all/details/astra-data-store/downloads-tab[NetApp Support Site^], you will get the following manifests:

*	astradscluster.yaml
*	astradsoperator.yaml
*	astradsversion.yaml
*	monitoring_operator.yaml

You will need to update the `astradscluster.yaml` manifest with your deployment-specific configuration. See link:../get-started/install-ads.html[Install Astra Data Store].

== Troubleshooting and support

With Astra Data Store, you can access community support using the NetApp Containers Slack channel. This channel is monitored by NetApp Support and our Technical Marketing Engineers.

https://netapp.io/slack[NetApp Container Slack channel^]


See link:../support/get-help-ads.html[Astra Data Store support operations].

*How do I raise a support case OR ask clarification on a quick question?*
To raise a support case or get clarification on a quick question, report your issue or question on the https://netapp.io/slack[NetApp Container Slack channel^]. NetApp Support will follow up with you to assist on a best-effort basis.

*How do I raise a request for a new feature?*
If you have questions on supported configurations or capabilities, reach out to astra.feedback@netapp.com.

*How do I generate a support log bundle?*
See link:../support/get-help-ads.html#generate-support-bundle-to-provide-to-netapp-support[Generate support bundle] for instructions on setting up and downloading support log bundles for Astra Data Store.

*Astra Data Store cannot find my Kubernetes node. How do I fix this?*
See link:../get-started/install-ads.html[Install Astra Data Store].

*Can IPv6 addresses be used for management, data, and cluster networks?*
No, Astra Data Store supports only IPv4 address. IPv6 support will be added in a future release of Astra Data Store.

*What NFS version is used while provisioning a volume on Astra Data Store?*
Astra Data Store supports NFS v4.1 for all volumes provisioned for Kubernetes applications and NFSv3 for all volumes provisioned for VMware workloads.


See link:../get-started/requirements.html[Astra Data Store requirements] and link:capabilities.html[Astra Data Store limits].

== Upgrading Astra Data Store
*Can I upgrade from Astra Data Store preview release?*
Yes. You can upgrade from the Astra Data Store Early Access Program release to a future release.
