---
sidebar: sidebar
permalink: get-started/install-ads.html
keywords: astra, astra data store, install, deploy, download
summary: To install Astra Data Store after addressing some environmental prerequisites, you'll download the bundle and install following the steps described.
---

= Install Astra Data Store
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

To install Astra Data Store, download the installation bundle from the NetApp Support Site and perform a series a commands to install it in your environment. You can use this procedure to install Astra Data Store in internet-connected or air-gapped environments.

.What you'll need
* link:requirements.html[Before you begin installation, prepare your environment for Astra Data Store deployment].
* Root administrative permissions.

.About this task
The Astra Data Store installation process guides you through the following high-level steps:

* <<Download the Astra Data Store bundle>>
* <<Unpack the bundle and change directory>>
* <<Copy the binary and push images to your local registry>>
* <<Install the monitoring operator>>
* <<Install the Astra Data Store operator>>
* <<Edit and apply the Astra Data Store Deployment YAML>>
* <<Install the Astra Data Store cluster>>
* <<Edit and apply the Astra Data Store license>>

== Download the Astra Data Store bundle
. Log in to the https://mysupport.netapp.com/site/products/all/details/astra-data-store-downloads-tab[NetApp Support Site^] and download the Astra Data Store bundle (`astra-data-store-[version].tar.gz`).
. Download the zip of Astra Data Store license file (NLF) from https://mysupport.netapp.com/site/products/all/details/astra-data-store/downloads-tab[NetApp Support Site^].
. (Optional) Use the following command to verify the signature of the bundle:
+
----
openssl dgst -sha256 -verify astra-data-store[version].pub -signature <astra-data-store[version].sig astra-data-store[version].tar.gz
----

== Unpack the bundle and change directory

. Extract the images:
+
----
tar -vxzf astra-data-store-[version].tar.gz
----

. Change to the Astra directory.
+
----
cd astra-data-store-[version]
----

. Define the path where the kubectl binary is to be installed. For example, `/usr/bin/kubectl` could be the binary path where kubectl is installed.
+
----
which kubectl
<install_path>
----

== Copy the binary and push images to your local registry

. Copy the kubectl-astrads binary to the standard path where k8s kubectl binaries are installed; for example, `/usr/bin/`. kubectl-astrads is a custom kubectl extension that installs and manages Astra Data Store clusters.
+
----
cp -f kubectl-astrads <path from previous command>
----

. Add the files in the Astra Data Store image directory to your local registry.
+
NOTE: See a sample script for the automatic loading of images below.

.. Log in to your registry:
+
----
docker login [your_registry_path]
----

.. Load the images into Docker.
.. Tag the images.
.. [[substep_image_local_registry_push]]Push the images to your local registry.

+
----
export REGISTRY=[your_registry_path]
for astraImageFile in $(ls images/*.tar)
  # Load to local cache. And store the name of the loaded image trimming the 'Loaded images: '
  do astraImage=$(docker load --input ${astraImageFile} | sed 's/Loaded image(s): //')
  astraImage=$(echo ${astraImage} | sed 's!localhost/!!')
  # Tag with local image repo.
  docker tag ${astraImage} ${REGISTRY}/${astraImage}
  # Push to the local repo.
  docker push ${REGISTRY}/${astraImage}
done
----

== Install the monitoring operator
(Optional) The monitoring operator is recommended if Astra Data Store monitoring will not be performed in Astra Control Center. You can install the monitoring operator if your Astra Data Store instance is a standalone deployment, uses Cloud Insights to monitor telemetry, or streams logs to a third-party endpoint such as Elastic.

. Run the install command:
----
helm3 install /u/samip/p4/netapp-monitoring --generate-name -n default
----

== Install the Astra Data Store operator
. List the Astra Data Store manifests:
+
----
ls manifests/
----
+
Response:
+
----
astradscluster.yaml
astradsoperator.yaml
astradsversion.yaml
----

. Edit the Astra Data Store operator custom resource definition (CRD) YAML to refer to the local registry (`your_registry_path`) you pushed the images to in a <<substep_image_local_registry_push,previous step>>:
+
----
sed -i 's/\[your_registry_path\]/docker.repo.customer.com/' astradsoperator.yaml
----

. Apply the changes to the file:
+
----
kubectl apply -f astradsoperator.yaml
----

. Verify that the Astra Data Store operator pod has started and is running:
+
----
kubectl get pods -n astrads-system
----
+
Response:
+
----
NAME                                READY   STATUS    RESTARTS   AGE
astrads-operator-5ffb94fbf-7ln4h    1/1     Running   0          17m
----

== Edit and apply the Astra Data Store Deployment YAML
. Edit the Astra Data Store deployment custom resource (CR) file to refer to the local registry (`your_registry_path`) you pushed the images to in a <<substep_image_local_registry_push,previous step>>:
+
----
sed -i 's/\[your_registry_path\]/docker.repo.customer.com/' astradsversion.yaml
----

. Apply the updated file:
+
----
kubectl apply -f astradsversion.yaml
----

== Edit and apply the Astra Data Store license

NOTE: For the Astra Data Store Preview release, the license type is limited to Evaluation.

. Apply the NetApp License File (NLF) that you obtained from the NetApp Support Site (NSS). Before you run the command, enter the name of the cluster (`<Astra-Data-Store-cluster-name>`) that you are <<Install the Astra Data Store cluster,going to deploy>> or have already deployed and the path to the license file (`<file_path/file.txt>`):
+
----
kubectl astrads license add --license-file-path <file_path/file.txt> --ads-cluster-name <Astra-Data-Store-cluster-name> -n astrads-system
----
+
Response:
+
----
astradslicense.astrads.netapp.io/e900000005 created
----

. Verify that license has been added:
+
----
kubectl get astradslicense -A
----
+
Response:
+
----
Status:
  Ads Cluster Name:  astrads-cluster-c62b612
  Configuration:
    Cluster Core Count Total:           45
    Cluster Storage Max Capacity Ti B:  240
  Last Autosupport:                     2021-10-29T19:19:47Z
  Last License Validation:              2021-10-29T19:25:13Z
  License Info:
    End Date:                  2022-01-23
    Entitlement Last Updated:  2021-10-26T18:26:14.882845
    Evaluation:                true
    Host ID:                   
      License Serial Number:     p100000006
      Product:                   Astra Data Store Preview
      Protocol:                  ADS_DEV_SUBS
----

== Install the Astra Data Store cluster
. Open the YAML file:
+
----
vim astradscluster.yaml
----

. Edit the following values in the YAML file.
+
NOTE: An example follows these steps.

.. In `metadata`, change the `name` string to the name of your cluster. This must be the same cluster name use when you <<Edit and apply the Astra Data Store license,apply the license>>.
.. Update the following required values in `spec`:
... Change the `mvip` string to the IP address of a floating management IP that is routable from any worker node in the cluster.
... In `adsDataNetworks`, list floating IP addresses (`addresses`) that are routable from any host where you intend to mount a NetApp volume.
... In `adsDataNetworks`, specify the netmask used by the data network.
... In `astraOptions`, add the license number (`serialNumber`) from the NLF.
... In `adsNodeConfig`, enter the per-node CPU core count and memory limits for the FireTap container.
.. For `monitoringConfig`, do one of the following:
* If you configured a <<Install the monitoring operator,monitoring operator>>, add the the namespace in which the agent CR (monitoring operator resource) is applied (default is `netapp-monitoring`) and the repo path for your registry (`your_registry_path`) that you used in previous steps.
* If you did not configure a <<Install the monitoring operator,monitoring operator>>, remove or comment out the `monitoringConfig` section.
.. (Optional) The following values can be optionally modified otherwise the default value will be used:
... In `spec`, enter a limit for how many nodes can be in the deployment (`adsNodeCount`).
... In `spec`, enter a selector label that filters out nodes for the cluster (`adsNodeSelector`).
...  In `spec`, provide a key that defines which protection domain a node belongs to (`adsProtectionDomainKey`).
... In `adsNetworkInterfaces`, enter the management, cluster, and storage interfaces.
... In `adsNodeConfig`, enter the per-node capacity, name of cache device to be configured for the FireTap container, and drive regex filter to select disks.

+
[subs=+quotes]
----
apiVersion: astrads.netapp.io/v1alpha1
kind: AstraDSCluster
metadata:
  *name: <name of your cluster>*
  namespace: astrads-system
spec:
  *mvip: <management IP address>*
  adsNodeCount: <optional node limit>
  adsNodeSelector: <optional selector label for node filtering>
  adsProtectionDomainKey: <optional key that defines which protection domain a node belongs to>
  adsDataNetworks:
    - *addresses: <CSV list of floating IP addresses>*
      *netmask: <The netmask used by dataNetworks>*
      gateway:
  adsNetworkInterfaces:
    managementInterface: <Management interface>
    clusterInterface: <Cluster interface>
    storageInterface: <Storage interface>
  astraOptions:
    *serialNumber: <serial number from license file>*
  adsNodeConfig:
    *cpu: <per-node cpu core count>*
    *memory: <per node memory limit>*
    capacity: <optional limit for per-node raw storage consumption>
    cacheDevice: <optional name of device to be configured as cache device for FireTap container>
    drivesFilter: <optional regex filter to select disks>
  *monitoringConfig:*
    *namespace: <namespace where applied>*
    *repo: <your_registry_path>*
  autoSupportConfig:
    historyRetentionCount: 10
    destinationURL: "https://testbed.netapp.com/put/AsupPut"
    periodic:
      - schedule: "0 0 * * 0"
        periodicconfig:
        - component:
            name: controlplane
            event: weekly
          userMessage: Weekly Control Plane AutoSupport bundle
----

. Apply the updated file:
+
----
kubectl apply -f astradscluster.yaml
----

. Verify the cluster deployment progress:
+
----
kubectl get astradscluster -n astrads-system
----
+
Sample return:
+
----
NAME                        STATUS    VERSION                            SERIAL NUMBER   MVIP           AGE

sample-0309d8b   created   sample-9.11.0-6090501   081856669       10.224.8.232   13d
----

== What's next

Complete the deployment by performing link:setup-ads.html[setup tasks].
