---
sidebar: sidebar
permalink: get-started/install-ads.html
keywords: astra, astra data store, install, deploy, download
summary: To install Astra Data Store after addressing some environmental prerequisites, you'll download the bundle and install following the steps described.
---

= Install Astra Data Store
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

To install Astra Data Store, download the installation bundle from the NetApp Support Site and complete installation steps described in this procedure.

.What you'll need
* link:requirements.html[Before you begin installation, prepare your environment for Astra Data Store deployment].
* Access to the NetApp Support Site. https://www.netapp.com/cloud-services/astra/data-store-form/[Register] for a preview if you don’t already have a full-access NetApp Support Site account.
* An active kubeconfig with cluster admin rights for the active context.
* Internet connectivity. Astra Data Store Preview does not support air-gapped environments. Internet connectivity is needed to reach support.netapp.com either directly or via a proxy.

.About this task
The Astra Data Store installation process guides you through the following high-level steps:

* <<Download the Astra Data Store bundle>>
* <<Unpack the bundle and change directory>>
* <<Copy the binary and push images to your local registry>>
* <<Install the Astra Data Store operator>>
* <<Apply the Astra Data Store version YAML>>
* <<Install the Astra Data Store cluster>>
* <<Apply the Astra Data Store license>>
* <<Configure Astra Data Store monitoring>>
* <<Install the monitoring operator>>

== Download the Astra Data Store bundle
. Log in to the https://mysupport.netapp.com/site/downloads/evaluation/astra-data-store/download[NetApp Support Site^] and download the Astra Data Store bundle (`astra-data-store-[version].tar.gz`).
//Need confirmation on tar name.
. Download the zip of Astra Data Store license file (NLF) from https://mysupport.netapp.com/site/downloads/evaluation/astra-data-store/download[NetApp Support Site^].
. (Optional) Use the following command to verify the signature of the bundle:
+
----
openssl dgst -sha256 -verify astra-data-store[version].pub -signature <astra-data-store[version].sig astra-data-store[version].tar.gz
----

== Unpack the bundle and change directory

. Extract the images:
+
----
tar -vxzf astra-data-store-[version].tar.gz
----

. Change to the Astra directory.
+
----
cd astra-data-store-[version]
----

. Define the path where the kubectl binary is to be installed.
+
NOTE: `/usr/bin/kubectl` is used as an example as the binary path. Replace it with your path before running the command.

+
----
which kubectl
/usr/bin/kubectl
----

== Copy the binary and push images to your local registry

. Copy the kubectl-astrads binary from the directory you used to extract images to the standard path where k8s kubectl binaries are installed; for example, `/usr/bin/`. kubectl-astrads is a custom kubectl extension that installs and manages Astra Data Store clusters.
+
----
cp -p ./bin/kubectl-astrads /usr/bin/.
----

. Add the files in the Astra Data Store image directory to your local registry.
+
NOTE: See a sample script for the automatic loading of images below.

.. Log in to your registry:
+
----
docker login [your_registry_path]
----

.. Load the images into Docker.
.. Tag the images.
.. [[substep_image_local_registry_push]]Push the images to your local registry.

+
----
export REGISTRY=[your_registry_path]
for astraImageFile in $(ls images/*.tar) ; do
   astraImage=$(docker load --input ${astraImageFile} | sed 's~Loaded image: ~~')
   astraImageShort=`echo $astraImage | sed 's~.*/~~'`
   docker tag ${astraImage} ${REGISTRY}/${astraImageShort}
   docker push ${REGISTRY}/${astraImageShort}
done
sed -i 's~\[YOUR REGISTRY\]~'${REGISTRY}'~' ./manifests/*.yaml
----

== Install the Astra Data Store operator
. List the Astra Data Store manifests:
+
----
ls manifests/*yaml
----
+
Response:
+
----
astradscluster.yaml
astradsoperator.yaml
astradsversion.yaml
monitoring_operator.yaml
----

. Deploy the operator using kubectl apply:
+
----
kubectl apply -f ./manifests/astradsoperator.yaml
----
+
Response:
+
----
namespace/astrads-system created
customresourcedefinition.apiextensions.k8s.io/astradsautosupports.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradscloudsnapshots.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsclusters.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsdeployments.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsexportpolicies.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsfaileddrives.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradslicenses.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsnfsoptions.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsnodeinfoes.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsqospolicies.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsvolumefiles.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsvolumes.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsvolumesnapshots.astrads.netapp.io created
role.rbac.authorization.k8s.io/astrads-leader-election-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradscloudsnapshot-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradscloudsnapshot-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradscluster-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradscluster-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradslicense-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradslicense-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsvolume-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsvolume-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-autosupport-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-autosupport-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-manager-role created
clusterrole.rbac.authorization.k8s.io/astrads-metrics-reader created
clusterrole.rbac.authorization.k8s.io/astrads-netappexportpolicy-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-netappexportpolicy-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-netappsdsdeployment-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-netappsdsdeployment-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-netappsdsnfsoption-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-netappsdsnfsoption-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-netappsdsnodeinfo-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-netappsdsnodeinfo-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-proxy-role created
rolebinding.rbac.authorization.k8s.io/astrads-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/astrads-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/astrads-proxy-rolebinding created
configmap/astrads-autosupport-cm created
configmap/astrads-firetap-cm created
configmap/astrads-fluent-bit-cm created
configmap/astrads-kevents-asup created
configmap/astrads-metrics-cm created
service/astrads-operator-metrics-service created
deployment.apps/astrads-operator created
----
. Verify that the Astra Data Store operator pod has started and is running:
+
----
kubectl get pods -n astrads-system
----
+
Response:
+
----
NAME                                READY   STATUS    RESTARTS   AGE
astrads-operator-5ffb94fbf-7ln4h    1/1     Running   0          17m
----

== Deploy the Astra Data Store version YAML

. Deploy using kubectl apply:
+
----
kubectl apply -f ./manifests/astradsversion.yaml
----

. Verify that the Astra Data Store version pod has started and is running:
+
----
kubectl get astradsversion -n astrads-system
----
+
Response:
+
----
NAME             AGE
astradsversion   1m
----

. Verify that the pods are running:
+
----
kubectl get pods -n astrads-system
----
+
Response:
+
----
NAME                                          READY   STATUS    RESTARTS   AGE
astrads-cluster-controller-7f6f884645-xxf2n   1/1     Running   0          117s
astrads-ds-nodeinfo-astradsversion-2jqnk      1/1     Running   0          2m7s
astrads-ds-nodeinfo-astradsversion-dbk7v      1/1     Running   0          2m7s
astrads-ds-nodeinfo-astradsversion-rn9tt      1/1     Running   0          2m7s
astrads-ds-nodeinfo-astradsversion-vsmhv      1/1     Running   0          2m7s
astrads-license-controller-fb8fd56bc-bxq7j    1/1     Running   0          2m2s
astrads-operator-5ffb94fbf-7ln4h              1/1     Running   0          2m10s
----

== Apply the Astra Data Store license

NOTE: For the Astra Data Store preview release, the license type is limited to preview.

. Apply the NetApp License File (NLF) that you obtained from the NetApp Support Site (NSS). Before you run the command, enter the name of the cluster (`<Astra-Data-Store-cluster-name>`) that you are <<Install the Astra Data Store cluster,going to deploy>> or have already deployed and the path to the license file (`<file_path/file.txt>`):
+
----
kubectl astrads license add --license-file-path <file_path/file.txt> --ads-cluster-name <Astra-Data-Store-cluster-name> -n astrads-system
----

. Verify that the license has been added:
+
----
kubectl astrads license list
----
+
Response:
+
----
NAME        ADSCLUSTER                  VALID   PRODUCT                     EVALUATION  ENDDATE     VALIDATED
p100000006  astrads-c6220-1011121314    true    Astra Data Store Preview    true        2022-01-23  2021-11-04T14:38:54Z
----

== Install the Astra Data Store cluster
. Open the YAML file:
+
----
vim ./manifests/astradscluster.yaml
----

. Edit the following values in the YAML file.
+
NOTE: An example follows these steps.

.. (Required) *Metadata*: In `metadata`, change the `name` string to the name of your cluster. This must be the same cluster name use when you <<Apply the Astra Data Store license,apply the license>>.
.. (Required) *Spec*: Change the following required values in `spec`:
* Change the `mvip` string to the IP address of a floating management IP that is routable from any worker node in the cluster.
* In `adsDataNetworks`, list floating IP addresses (`addresses`) that are routable from any host where you intend to mount a NetApp volume.
* In `adsDataNetworks`, specify the netmask used by the data network.
//ADD adsNetworkInterfaces step? Need to add managementInterface for host. Specify a specific interface for cluster and storage.
.. (Optional) *monitoringConfig*: If you want to configure a <<Install the monitoring operator,monitoring operator>> (optional if you are not using Astra Control Center for monitoring), remove the commenting from the section, add the namespace in which the agent CR (monitoring operator resource) is applied (default is `netapp-monitoring`), and add the repo path for your registry (`your_registry_path`) that you used in previous steps.
.. (Optional) *autoSupportConfig*: Retain the link:../support/autosupport.html[AutoSupport] default values unless you need to configure a proxy:
* For `proxyURL`, set the URL of the proxy with the port that will be used for AutoSupport bundle transfer.

+
NOTE: Most comments have been removed from the YAML sample below.

+
[subs=+quotes]
----
apiVersion: astrads.netapp.io/v1alpha1
kind: AstraDSCluster
*metadata:*
  *name: astrads-cluster-name*
  namespace: astrads-system
*spec:*
  adsNodeConfig:
    cpu: 9
    memory: 34
  adsNodeCount: 4
  *mvip: ""*
  *adsDataNetworks:*
    *- addresses: ""*
      *netmask:*
  adsNetworkInterfaces:
    managementInterface: "mgmt"
    clusterInterface: "data"
    storageInterface: "data"
  # [Optional] Provide a monitoring config to be used to setup/configure a monitoring agent.
 *# monitoringConfig:*
   *# namespace: "netapp-monitoring"*
   *# repo: "[YOUR REGISTRY]"*
  autoSupportConfig:
    autoUpload: true
    enabled: true
    coredumpUpload: false
    historyRetentionCount: 25
    destinationURL: "https://support.netapp.com/put/AsupPut"
    # ProxyURL defines the URL of the proxy with port to be used for AutoSupport bundle transfer
    *# proxyURL:*
    periodic:
      - schedule: "0 0 * * *"
        periodicconfig:
        - component:
            name: storage
            event: dailyMonitoring
          userMessage: Daily Monitoring Storage AutoSupport bundle
          nodes: all
        - component:
            name: controlplane
            event: daily
          userMessage: Daily Control Plane AutoSupport bundle
----

. Deploy the cluster using kubectl apply:
+
----
kubectl apply -f ./manifests/astradscluster.yaml
----

. Verify the cluster deployment progress:
+
----
kubectl get astradscluster -n astrads-system
----
+
Sample return:
+
----
NAME                        STATUS    VERSION    SERIAL NUMBER    MVIP       AGE

astrads-c6220-1011121314   created   2021.10.0   p100000006       10.x.x.x   2m
----

== Configure Astra Data Store monitoring
You can configure Astra Data Store for Astra Control Center monitoring or for monitoring by another telemetry service.

=== Configure monitoring for Astra Control Center
Perform the following step only after Astra Data Store is managed as a backend in Astra Control Center.

. Configure Astra Data Store for monitoring by Astra Control Center:
+
----
kubectl astrads monitoring -m netapp-monitoring -r [YOUR REGISTRY] setup
----

=== Install the monitoring operator
(Optional) The monitoring operator is recommended only if Astra Data Store monitoring will not be performed in Astra Control Center. You can install the monitoring operator if your Astra Data Store instance is a standalone deployment, uses Cloud Insights to monitor telemetry, or streams logs to a third-party endpoint such as Elastic.

. Run this install command:
+
----
kubectl apply -f ./manifests/monitoring_operator.yaml
----

. Configure Astra Data Store for monitoring:
+
----
kubectl astrads monitoring -m netapp-monitoring -r [YOUR REGISTRY] setup
----

== What's next

Complete the deployment by performing link:setup-ads.html[setup tasks].
