---
sidebar: sidebar
permalink: get-started/install-ads.html
keywords: astra, astra data store, install, deploy, download
summary: To install Astra Data Store after addressing some environmental prerequisites, you'll download the bundle and install following the steps described.
---

= Install Astra Data Store
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

To install Astra Data Store, download the installation bundle from the NetApp Support Site and complete installation steps described in this procedure.

.What you'll need
* link:requirements.html[Before you begin installation, prepare your environment for Astra Data Store deployment].
* Access to the NetApp Support Site. https://www.netapp.com/cloud-services/astra/data-store-form/[Register] for a preview if you don’t already have a full-access NetApp Support Site account.
* Root or administrative permissions to your Kubernetes cluster.
* Internet connectivity. Astra Data Store Preview does not support air-gapped environments.

.About this task
The Astra Data Store installation process guides you through the following high-level steps:

* <<Download the Astra Data Store bundle>>
* <<Unpack the bundle and change directory>>
* <<Copy the binary and push images to your local registry>>
* <<Install the monitoring operator>>
* <<Install the Astra Data Store operator>>
* <<Apply the Astra Data Store version YAML>>
* <<Install the Astra Data Store cluster>>
* <<Apply the Astra Data Store license>>

== Download the Astra Data Store bundle
. Log in to the https://mysupport.netapp.com/site/products/all/details/astra-data-store-downloads-tab[NetApp Support Site^] and download the Astra Data Store bundle (`astra-data-store-[version].tar.gz`).
. Download the zip of Astra Data Store license file (NLF) from https://mysupport.netapp.com/site/products/all/details/astra-data-store/downloads-tab[NetApp Support Site^].
. (Optional) Use the following command to verify the signature of the bundle:
+
----
openssl dgst -sha256 -verify astra-data-store[version].pub -signature <astra-data-store[version].sig astra-data-store[version].tar.gz
----

== Unpack the bundle and change directory

. Create a directory:
+
----
mkdir astra-data-store-[version]
----

. Change to the Astra directory.
+
----
cd astra-data-store-[version]
----

. Extract the images:
+
----
tar -vxzf astra-data-store-[version].tar.gz
----

. Define the path where the kubectl binary is to be installed.
+
NOTE: `/usr/bin/kubectl` is used as an example as the binary path. Replace it with your path before running the command.

+
----
which kubectl
/usr/bin/kubectl
----

== Copy the binary and push images to your local registry

. Copy the kubectl-astrads binary from the directory you used to extract images to the standard path where k8s kubectl binaries are installed; for example, `/usr/bin/`. kubectl-astrads is a custom kubectl extension that installs and manages Astra Data Store clusters.

----
cp -f ./bin/kubectl-astrads
----

. Add the files in the Astra Data Store image directory to your local registry.
+
NOTE: See a sample script for the automatic loading of images below.

.. Log in to your registry:
+
----
docker login [your_registry_path]
----

.. Load the images into Docker.
.. Tag the images.
.. [[substep_image_local_registry_push]]Push the images to your local registry.

+
----
export REGISTRY=[your_registry_path]

for astraImageFile in $(ls images/*.tar) ; do
   astraImage=$(docker load --input ${astraImageFile} | sed 's/Loaded image: //')
   docker tag ${astraImage} ${REGISTRY}/${astraImage}
   docker push ${REGISTRY}/${astraImage}
done
----

== Install the monitoring operator
(Optional) The monitoring operator is recommended if Astra Data Store monitoring will not be performed in Astra Control Center. You can install the monitoring operator if your Astra Data Store instance is a standalone deployment, uses Cloud Insights to monitor telemetry, or streams logs to a third-party endpoint such as Elastic.

. Replace `[YOUR REGISTRY]` with the path to your image registry:
+
----
sed -i 's/\[YOUR REGISTRY]/docker.repo.example.com/' astradsoperator.yaml
----

. Run the install command:
+
----
kubectl apply -f  monitoring_operator.yaml
----


== Install the Astra Data Store operator
. List the Astra Data Store manifests:
+
----
ls manifests/
----
+
Response:
+
----
astradscluster.yaml
astradsoperator.yaml
astradsversion.yaml
----

. Edit the Astra Data Store operator custom resource definition (CRD) YAML to refer to the local registry you pushed the images to in a <<substep_image_local_registry_push,previous step>>:
+
NOTE: Replace `docker.repo.example.com` with your repo path before running the command.

+
----
sed -i 's/\[YOUR REGISTRY\]/docker.repo.example.com/' astradsoperator.yaml
----

. Apply the changes to the file:
+
----
kubectl apply -f astradsoperator.yaml
----
+
Response:
+
----
namespace/astrads-system created
customresourcedefinition.apiextensions.k8s.io/astradsautosupports.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradscloudsnapshots.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsclusters.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsdeployments.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsexportpolicies.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsfaileddrives.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradslicenses.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsnfsoptions.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsnodeinfoes.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsqospolicies.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsvolumefiles.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsvolumes.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsvolumesnapshots.astrads.netapp.io created
role.rbac.authorization.k8s.io/astrads-leader-election-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradscloudsnapshot-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradscloudsnapshot-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradscluster-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradscluster-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradslicense-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradslicense-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsvolume-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsvolume-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-autosupport-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-autosupport-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-manager-role created
clusterrole.rbac.authorization.k8s.io/astrads-metrics-reader created
clusterrole.rbac.authorization.k8s.io/astrads-netappexportpolicy-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-netappexportpolicy-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-netappsdsdeployment-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-netappsdsdeployment-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-netappsdsnfsoption-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-netappsdsnfsoption-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-netappsdsnodeinfo-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-netappsdsnodeinfo-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-proxy-role created
rolebinding.rbac.authorization.k8s.io/astrads-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/astrads-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/astrads-proxy-rolebinding created
configmap/astrads-autosupport-cm created
configmap/astrads-firetap-cm created
configmap/astrads-fluent-bit-cm created
configmap/astrads-kevents-asup created
configmap/astrads-metrics-cm created
service/astrads-operator-metrics-service created
deployment.apps/astrads-operator created
----

. Verify that the Astra Data Store operator pod has started and is running:
+
----
kubectl get pods -n astrads-system
----
+
Response:
+
----
NAME                                READY   STATUS    RESTARTS   AGE
astrads-operator-5ffb94fbf-7ln4h    1/1     Running   0          17m
----

== Apply the Astra Data Store version YAML
. Edit the Astra Data Store version custom resource (CR) file to refer to the local registry you pushed the images to in a <<substep_image_local_registry_push,previous step>>:
+
NOTE: Replace `docker.repo.example.com` with your repo path before running the command.

+
----
sed 's~\[YOUR REGISTRY\]~docker.repo.example.com~' ./manifests/astradsoperator.yaml > astradsoperator.yaml
----

. Apply the updated file:
+
----
kubectl apply -f astradsversion.yaml
----

== Apply the Astra Data Store license

NOTE: For the Astra Data Store preview release, the license type is limited to preview.

. Apply the NetApp License File (NLF) that you obtained from the NetApp Support Site (NSS). Before you run the command, enter the name of the cluster (`<Astra-Data-Store-cluster-name>`) that you are <<Install the Astra Data Store cluster,going to deploy>> or have already deployed and the path to the license file (`<file_path/file.txt>`):
+
----
kubectl astrads license add --license-file-path <file_path/file.txt> --ads-cluster-name <Astra-Data-Store-cluster-name> -n astrads-system
----

. Verify that the license has been added:
+
----
kubectl astrads license list
----
+
Response:
+
----
NAME        ADSCLUSTER                  VALID   PRODUCT                     EVALUATION  ENDDATE     VALIDATED
p100000006  astrads-c6220-1011121314    true    Astra Data Store Preview    true        2022-01-23  2021-11-04T14:38:54Z
----

== Install the Astra Data Store cluster
. Open the YAML file:
+
----
vim astradscluster.yaml
----

. Edit the following values in the YAML file.
+
NOTE: An example follows these steps.

.. (Required) *Metadata*: In `metadata`, change the `name` string to the name of your cluster. This must be the same cluster name use when you <<Apply the Astra Data Store license,apply the license>>.
.. (Required) *Spec*: Change the following required values in `spec`:
* Change the `mvip` string to the IP address of a floating management IP that is routable from any worker node in the cluster.
* In `adsDataNetworks`, list floating IP addresses (`addresses`) that are routable from any host where you intend to mount a NetApp volume.
* In `adsDataNetworks`, specify the netmask used by the data network.
.. (Required) *monitoringConfig*: For `monitoringConfig`, do one of the following:
* If you configured a <<Install the monitoring operator,monitoring operator>>, add the the namespace in which the agent CR (monitoring operator resource) is applied (default is `netapp-monitoring`) and the repo path for your registry (`your_registry_path`) that you used in previous steps.
* If you did not configure a <<Install the monitoring operator,monitoring operator>>, remove or comment out the `monitoringConfig` section.
.. (Optional) *autoSupportConfig*: Change the following link:../support/autosupport.html[AutoSupport] values or use the default values:
* For `historyRetentionCount`, enter a limit for the number of ASUPs present in a system at any given time.
* For `coredumpUpload`, enter `true` if core dumps should be uploaded to backend by default.
* For `autoUpload`, retain the setting of `true` for the Astra Data Store preview edition.
* For `destinationURL`, enter the backend URL where ASUPs will be uploaded.
* In `periodicconfig`, enter the `event` ASUP reporting frequency for each system component.
.. (Optional) Change the following values or use the default values:
* In `spec`, enter a limit for how many nodes can be in the deployment (`adsNodeCount`).
* In `spec`, enter a selector label that filters out nodes for the cluster (`adsNodeSelector`).
* In `adsNetworkInterfaces`, enter the management, cluster, and storage interfaces.
* In `adsNodeConfig`, enter the per-node capacity, name of cache device to be configured for the FireTap container, and drive regex filter to select disks.

+
[subs=+quotes]
----
apiVersion: astrads.netapp.io/v1alpha1
kind: AstraDSCluster
metadata:
  *name: <name of your cluster>*
  namespace: astrads-system
spec:
  *mvip: <management IP address>*
  adsNodeCount: <optional node limit>
  adsNodeSelector: <optional selector label for node filtering>
  adsDataNetworks:
    - *addresses: <CSV list of floating IP addresses>*
      *netmask: <The netmask used by dataNetworks>*
      gateway:
  adsNetworkInterfaces:
    managementInterface: <Management interface>
    clusterInterface: <Cluster interface>
    storageInterface: <Storage interface>
  adsNodeConfig:
    capacity: <optional limit for per-node raw storage consumption>
    cacheDevice: <optional name of device to be configured as cache device for FireTap container>
    drivesFilter: <optional regex filter to select disks>
  *monitoringConfig:*
    *namespace: <namespace where applied>*
    *repo: <your_registry_path>*
  autoSupportConfig:
    historyRetentionCount: 10
    coredumpUpload: false
    autoUpload: true
    destinationURL: "https://example.com/put/AsupPut"
    periodic:
      - schedule: "0 0 * * *"
        periodicconfig:
        - component:
            name: controlplane
            event: daily
          userMessage: Daily Control Plane AutoSupport bundle
        - component:
            name: storage
            event: dailyMonitoring
          nodes: all
          userMessage: Daily Monitoring Storage AutoSupport bundle
----

. Apply the updated file:
+
----
kubectl apply -f astradscluster.yaml
----

. Verify the cluster deployment progress:
+
----
kubectl get astradscluster -n astrads-system
----
+
Sample return:
+
----
NAME                        STATUS    VERSION                            SERIAL NUMBER   MVIP           AGE

sample-0309d8b   created   sample-9.11.0-6090501   081856669       10.224.8.232   13d
----

== What's next

Complete the deployment by performing link:setup-ads.html[setup tasks].
