---
sidebar: sidebar
permalink: get-started/requirements.html
keywords: kubernetes cluster, cluster requirements, version requirements, supported versions, apps, supported apps, mariadb, mysql, postgres, kubernetes version, ubuntu, image type, networking
summary: Get started by verifying support for your environment.
---

= Astra Data Store requirements
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

Get started by verifying that your environment meets Astra Data Store preview requirements.

//POLARIS-458
////
== Minimum resource requirements for each node
These are the minimum resource requirements for each node in an Astra Data Store preview cluster:

//* Minimum number of drives: 2
* Minimum number of physical CPU cores: 4
* Minimum number of vCPUs: 10
* Minimum RAM per node: 36GB
* Minimum networking bandwidth: 10GbE
* Minimum storage capacity: 1TB
* Minimum number of data drives: 3
* Minimum available storage capacity: 100GiB
* Minimum number of cache devices: 1 (8GB or greater in size)
////

== Individual node resource requirements and capabilities
These are the minimum resource requirements and maximum capabilities for each node in an Astra Data Store preview cluster:
|===
|Resource |Minimum |Maximum

|Number of data drives
|3
|N/A

|Number of physical CPU cores
|4
|N/A

|Number of vCPUs
|10
|N/A

|RAM
|36GB
|N/A

|Networking bandwidth
|10GbE
|N/A

|Total storage capacity
|1TB
|N/A

|Available storage capacity
|100GiB
|N/A

|Number of cache devices
|1 (8GB or greater in size)
|N/A

|Provisioned capacity
|N/A
|1TiB

|Usable raw capacity per node
|N/A
|4TiB
|===

== Cluster resource requirements and capabilities
Each Astra Data Store preview cluster has the following minimum requirements and maximum capabilities:

|===
|Resource |Minimum |Maximum

|Cluster size
|4 worker nodes, 1 master node
|4 worker nodes, 1 master node

|Volume size
|1GiB
|1TB

|Drive size
|100GiB
|N/A

|Number of volumes
|N/A
|10 per node

|Number of snapshots per volume
|N/A
|256

|Number of data drives
|N/A
|14
|===

////
* Minimum cluster size: 4 worker nodes, 1 master node
* Minimum volume size: 1GiB
* Minimum drive size: 100GiB
////


////
== Maximum capabilities for each node
Each node in an Astra Data Store preview cluster has the following capabilities:


* Maximum provisioned capacity per node: 1TiB
//* Max usable (aka raw) capacity per node: 48TiB
* Max usable (aka raw) capacity per node: 4TiB
////

//POLARIS-479
////
== Maximum capabilities for a cluster
Astra Data Store preview has the following cluster capabilities:


* Maximum cluster size: 5 nodes
* Maximum volume size: 1TB
* Maximum number of volumes per Astra Data Store cluster: 10 per node
* Maximum number of snapshots per volume: 256
//* Maximum capacity per drive: 15.36TB
//* Maximum number of drives per node: 24
//* Maximum number of nodes per cluster: 40
* Maximum number of data drives: 14
////

////
.Premium license
* Maximum cluster size: 40 nodes
* Maximum volume size: 100TB
* Maximum number of volumes per Astra Data Store cluster: 4000
* Maximum number of snapshots per volume: 256
* Maximum capacity per drive: 15.36TB
* Maximum number of drives per node: 24
* Maximum number of nodes per cluster: 40
* Maximum number of data drives: 14
////

//POLARIS-2175
== Hardware and software requirements
Astra Data Store preview has been validated on the following hardware and software platforms.

.Hardware platforms
* HPE DL360
* HPE DL380
* Dell R640
* Dell R740

.Software
* Operating systems:
** Red Hat Enterprise Linux 7.9
** Red Hat Enterprise Linux 8.2
** Red Hat Enterprise Linux CoreOS (RHCOS)
** Ubuntu 20.04
* Kubernetes distributions:
** Red Hat OpenShift 4.6
** Red Hat OpenShift 4.7
** Google Anthos 1.7
** Upstream Kubernetes 1.20
** Upstream Kubernetes 1.21
** Upstream Kubernetes 1.22

//POLARIS-461
.Storage
Astra Data Store preview clusters support SAS and NVMe TLC SSD storage with the following capabilities:

* Each of the Kubernetes worker nodes which are part of the Astra Data Store preview deployment should have the same type and number of physical disks.
* The drives need to be addressable as SCSI devices, and each drive must have a unique serial number.
* RAID configurations are not supported (if you use a RAID controller, enable "pass-through" mode).

== Licensing
Astra Data Store preview requires an Astra Data Store preview license for full functionality. Obtain a preview license from the NetApp Support Site.

== Networking requirements
Astra Data Store preview needs a certain network interface and IP address configuration for the management, cluster, and data networks.

.Network interface requirements
* Minimum configuration: One 10GbE or faster network interface
+
NOTE: If unspecified, the interface that hosts the management IP address (MIP) is used for all 3 networks (management, cluster and data).

* Maximum configuration: Two network interfaces
** One 1GbE or faster interface for the management network
** One 10GbE or faster interface for the data network

NOTE: The cluster network should reside on the same interface as either the management network (if the management network is 10GbE or faster), or the data network.

.IP address requirements
* Management network
** One IPv4 address (pre-configured) for the management IP address (MIP) of each node
** One IPv4 address (free/spare/unconfigured) for the management virtual IP address (MVIP) of the cluster. This address is configured on the management network interface during Astra Data Store preview cluster installation.
* Cluster network
** One IPv4 address (pre-configured) for the cluster IP address of each node on the data network interface. As an alternative, the MIP of the management network interface can be used only if the MIP is hosted on a 10GbE or faster interface.
* Data network
** One IPv4 address (free/spare/unconfigured) for the volume's export address of each node. This address is configured on the data network interface during Astra Data Store preview cluster installation.


//POLARIS-656 - more questions here for HA requirements (Naveen M is SME)
//== High availability requirements
//Astra Data Store requires Element 12.3 or later for high availability to function correctly. High availability makes use of the Element software Protection Domains feature.

//POLARIS-654 and POLARIS-450
== Persistent volume sharing requirements
Each Astra Data Store preview cluster supports using persistent volumes to cover the storage needs of any apps installed on that cluster. Persistent volumes in Astra Data Store preview have the following requirements and capabilities:

.Requirements
* NFS 4.1 client/server in Kubernetes clusters
* Kubernetes apps will access files through persistent volumes shared over NFS 4.1, which requires the AUTH_SYS authentication method.

.Capabilities
* Parallel NFS (pNFS) is not supported.
* Only IP-based export policies are supported.

//POLARIS-1285 - Do we want to document ports that ASDS uses?
// ADS just needs standard ports that K8S uses
////
== Required TCP ports
Astra Data Store requires that you open the following ports in your edge firewall:

|===
|Port |Description

|Port
|Description

|Port
|Description

|Port
|Description

|Port
|Description

|Port
|Description

|Port
|Description

|Port
|Description

|===

////
////
//POLARIS-2317 and 2316
== Astra Data Store Starter Edition feature and expansion capabilities
Astra Data Store Starter Edition has certain feature and expansion limitations.

.Minimum resource requirements
The minimum memory requirement per node is 32GB.

.Feature capabilities
* NFS vVols are not supported
* A connection to the cloud is required

.Expansion capabilities

|===
|Resource |Limits

|Number of nodes in a cluster
|5

|Persistent volumes per node
|10

|vCPU cores per node
|9

|vCPU cores per Cluster
|45

|Max. Capacity per node
|1TiB

|Max. Capacity per Cluster
|4TiB + 1TiB

|Max. Capacity per Volume
|1TiB
|===

////

== What's next

View the link:quick-start.html[quick start] overview.
