---
sidebar: sidebar
permalink: get-started/requirements.html
keywords: kubernetes cluster, cluster requirements, version requirements, supported versions, apps, supported apps, mariadb, mysql, postgres, kubernetes version, ubuntu, image type, networking
summary: Get started by verifying support for your environment.
---

= Astra Data Store requirements
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

Get started by verifying that your environment meets Astra Data Store requirements.

//POLARIS-654
== Persistent volume sharing requirements

* NFS 4.1 client/server in Kubernetes clusters
* K8S apps will access files through persistent volumes shared over NFS 4.1, using the AUTH_SYS authentication method.
* Parallel NFS (pNFS) is not supported.
* Only IP-based export policies are supported.

//POLARIS-458
== Node physical resource requirements
A minimum size cluster of Astra SDS is 3 nodes. The minimum resource requirements for each node in an Astra SDS cluster are as follows:

* Minumum number of drives: 2
* Minimum number of CPU cores: 4
* Minimum RAM: 4GB
* Minimum number of NW BW: 10Gb
* Minimum storage capacity: 1TB

//POLARIS-460
//dissimilar node types are supported for scale
== Astra SDS cluster expansion requirements
Astra SDS supports dissimilar node types in a cluster. If you are expanding a cluster, any node capability is supported for the new node, as long as the new node's performance is not lower than the lowest performing node in the cluster. All nodes, including new nodes during an expansion, must meet the requirements in <<Node physical resource requirements>>.

//POLARIS-461
== Supported media types in Astra SDS
Astra SDS clusters support SAS and NVMe TLC SSD storage, with the following capabilities:

* Maximum capacity per drive: 15.36TB
* Maximum number of drives per node: 24
* Maximum number of nodes per cluster: 40

//POLARIS-656 - more questions here for HA requirements (Naveen M is SME)
== Astra SDS high availability requirements
Astra SDS requires Element 12.3 or later for high availability to function correctly. It makes use of Protection Domains.

//POLARIS-2175
== Astra SDS hardware and software requirements
Astra SDS requires the following hardware and software configuration on each node:

.Software
* Operating systems: Red Hat Enterprise Linux 7.7 and 8.2
* Kubernetes distribution: OpenShift 4.6, Anthos 1.7
* Kubernetes version: 1.19

.Hardware
* HPE DL360
* HPE DL380
* Dell R640
* Dell R740

//POLARIS-2317 and 2316
== Feature and expansion limitations of Astra SDS Starter Edition
Astra SDS Starter Edition has certain feature and expansion limitations.

.Minimum resource requirements
Min. Memory requirement per node: 32GiB

.Feature limitations
* NFS vVols are not supported
* Cloud connection is required

.Expansion limitations
|===
|Resource |Limits

|Number of nodes in a cluster
|5

|Persistent volumes per node
|10

|vCPU cores per node
|9

|vCPU cores per Cluster
|45

|Max. Capacity per node
|1TiB

|Max. Capacity per Cluster
|4TiB + 1TiB

|Max. Capacity per Volume
|1TiB

|===


//POLARIS-450
== PV requirements of apps










== Kubernetes cluster general requirements

A Kubernetes cluster must meet the following general requirements so you can discover and manage it from Astra Control Center.

* *Image registry*: You must have an existing private Docker image registry to which you can push Astra Control Center build images. You must have the URL of the image registry where you will upload the images, and you must have tagged the images for the private container registry.

* *Trident / ONTAP storage configuration*: Astra Control Center requires that Trident version 21.01 or 21.04 already be installed and configured to work with NetApp ONTAP version 9.5 or newer as the storage backend. Astra Control Center requires that a storage class be created and set as the default storage class. Astra Control Center supports the following ONTAP drivers provided by Trident:

** ontap-nas
** ontap-nas-flexgroup
** ontap-san
** ontap-san-economy

If you are planning to manage the Kubernetes cluster from Astra Control Center as well as use the cluster to host the Astra Control Center installation, the cluster has the following additional requirements:

* The most recent version of the Kubernetes https://kubernetes-csi.github.io/docs/snapshot-controller.html[snapshot-controller component^] is installed
* A Trident https://netapp-trident.readthedocs.io/en/latest/kubernetes/concepts/objects.html?highlight=VolumeSnapshotClass#kubernetes-volumesnapshotclass-objects[volumesnapshotclass object^] has been defined by an administrator
* A default Kubernetes storage class exists on the cluster
* At least one storage class is configured to use Trident

=== OpenShift clusters
Astra Control Center requires a Red Hat OpenShift Container Platform 4.6.8 or 4.7 cluster that has Trident storage classes backed by ONTAP 9.5 or newer, with the following attributes:

* At least 300GB of available ONTAP storage capacity
* 3 controller nodes with 4 CPU cores, 16GB RAM, and 120GB of available storage each
* 3 worker nodes with at least 8 CPU cores, 16GB RAM, and 50GB of available storage each
* A load balancer which exposes a reachable IP address
* A method for pointing the FQDN of Astra Control Center to the load balanced IP address
* Kubernetes version 1.19 or 1.20

Make sure that your cluster meets the minimum requirements and that you follow Kubernetes best practices so that Astra Control Center is highly available in your Kubernetes cluster.

NOTE: OpenShift 4.8 is not supported.

[NOTE]
======================
During app cloning, Astra Control Center needs to allow OpenShift to mount volumes and change the ownership of files. Because of this, ONTAP needs to be configured to allow volume operations to complete successfully using the following commands:

. `export-policy rule modify -vserver svm0 -policyname default -ruleindex 1 -superuser sys`
. `export-policy rule modify -policyname default -ruleindex 1 -anon 65534`
======================

NOTE: If you plan to add a second OpenShift 4.6 or 4.7 cluster as a managed compute resource, you need to ensure that the Trident Volume Snapshot feature is enabled. See the official Trident https://netapp-trident.readthedocs.io/en/stable-v21.04/kubernetes/operations/tasks/volumes/snapshots.html?highlight=volumesnapshot#on-demand-volume-snapshots[instructions^] to enable and test Volume Snapshots with Trident.

////
=== Non-OpenShift Kubernetes clusters
The Kubernetes cluster you use for Astra Control Center should already be deployed in your environment and you should have permissions to manage the cluster. This cluster should be preconfigured with the following:

* A load balancer with a static IP address or IP address range
* An internal domain name that is routed from an internal DNS server and points to the static IP address or IP address range of the cluster (the DNS name should point to the load-balanced IP address or addresses using the internal DNS server)
* A default storage provider in the Kubernetes cluster that is backed by a Trident storage class to work with ONTAP
* A single Trident StorageClass configured as the default
* Kubernetes version 1.18, 1.19, or 1.20
* At least 3 worker nodes
////

=== App management requirements
Astra Control Center has the following app management requirements:

* *Licensing*: You need an Astra Control Center license to manage apps using Astra Control Center.
* *Helm 3*: If you use Helm to deploy apps, Astra Control Center requires Helm version 3. Managing and cloning apps deployed with Helm 3 (or upgraded from Helm 2 to Helm 3) are fully supported. Apps deployed with Helm 2 are not supported.
* *Operator management*: Astra Control Center does not support apps that are deployed with Operator Lifecycle Manager (OLM)-enabled operators or cluster-scoped operators.

== Access to the internet

You should determine whether you have outside access to the internet. If you do not, some functionality might be limited, such as receiving monitoring and metrics data from NetApp Cloud Insights, or sending support bundles to the NetApp Support Site.
////
If you do have access to the internet, decide which of the following NetApp systems you will authorize Astra Control Center to integrate with:

* Cloud Insights for monitoring and metrics
* NetApp Support Site for Active IQ and SmartSolve processing
//* IPA for license automation
////

== License

Astra Control Center requires an Astra Control Center license for full functionality. Obtain an evaluation license or full license from NetApp. Without a license, you will be unable to:

// * Add clusters (de-scoped for Q2 release)
* Define custom apps
* Create snapshots or clones of existing apps
* Configure data protection policies

If you want to try Astra Control Center, you can link:setup_overview.html#add-a-full-or-evaluation-license[use a 90-day evaluation license].

== Load balancing

Astra Control Center requires the Kubernetes cluster to have a load balancer installed and configured with an accessible external IP address. In the internal DNS server configuration, you should point the chosen DNS name for Astra Control Center to the load-balanced IP address.

== Networking requirements

The cluster that hosts Astra Control Center communicates using the following TCP ports. You should ensure that these ports are allowed through any firewalls, and configure firewalls to allow any HTTPS egress traffic originating from the Astra network. Some ports require connectivity both ways between the cluster hosting Astra Control Center and each managed cluster (noted where applicable).

|===
|Product |Port |Protocol |Direction |Purpose

|Astra Control Center
|443
|HTTPS
|Ingress
|UI / API access - Ensure this port is open both ways between the cluster hosting Astra Control Center and each managed cluster

|Astra Control Center
|9090
|HTTPS
a|

* Ingress (to cluster hosting Astra Control Center)
* Egress (random port from the node IP address of each worker node of each managed cluster)

|Metrics data to metrics consumer - ensure each managed cluster can access this port on the cluster hosting Astra Control Center

|Trident
|34571
|HTTPS
|Ingress
|Node pod communication

|Trident
|9220
|HTTP
|Ingress
|Metrics endpoint
|===

////
// Removed at request of Pat Nanto
|n/a
|HTTPS
|Egress
|Data to Cloud Insights

|n/a
|HTTPS
|Egress
|Log processing data to logs consumer

|n/a
|HTTPS
|Egress
|NetApp AutoSupport messages to NetApp Active IQ

|n/a
|HTTPS
|Egress
|Bucket service communication with bucket provider

|n/a
|HTTPS
|Egress
|Metrics flow from ONTAP

|n/a
|HTTPS
|Egress
|Storage Backend service communication with ONTAP

|n/a
|HTTPS
|Egress
|Cloud extension communication with managed cluster

|n/a
|HTTPS
|Egress
|Nautilus communication with managed cluster - ensure the corresponding Nautilus port is open for each managed cluster

|n/a
|HTTPS
|Egress
|Trident service communication with each managed cluster’s Trident instance
////

== Supported web browsers

Astra Control Center supports recent versions of Firefox, Safari, and Chrome with a minimum resolution of 1280 x 720.

////
== Integration with your organization

Before you deploy Astra Control Center, you should determine which internal integrations should occur, including the following:

* Single sign on
* SMTP server for email notifications

If you want to integrate these options, you should obtain the following:

* SSO integration confirmation details
* SMTP server configuration details
////
== What's next

View the link:quick-start.html[quick start] overview.
