---
sidebar: sidebar
permalink: get-started/requirements.html
keywords: kubernetes cluster, cluster requirements, version requirements, supported versions, apps, supported apps, mariadb, mysql, postgres, kubernetes version, ubuntu, image type, networking
summary: Get started by verifying support for your environment.
---

= Astra Data Store requirements
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

Get started by verifying that your environment meets Astra Data Store requirements.

== Licensing
Astra Data Store requires an Astra Data Store license for full functionality. Obtain an evaluation license or full license from the NetApp Support Site.

//POLARIS-2175
== Astra Data Store hardware and software requirements
Astra Data Store requires the following hardware and software configuration on each node:

.Software
* Operating systems: Red Hat Enterprise Linux 7.7 and 8.2
* Kubernetes distribution: OpenShift 4.6, Anthos 1.7
* Kubernetes version: 1.19

.Hardware
* HPE DL360
* HPE DL380
* Dell R640
* Dell R740

== Networking requirements
Astra Data Store needs a certain network interface and IP address configuration for the management, cluster, and data networks.

.Network interfaces
* Minimum configuration: One 10GbE or faster network interface
If unspecified then the interface hosting MIP will be used for all the 3 networks (management, cluster and data)
* Maximum configuration: Two network interfaces
** One 1GbE or faster interface for the management network
** One 10GbE or faster interface for the data network

NOTE: The cluster network should reside on the same interface as either the management network (if the management network is 10GbE or faster), or the data network.

.IP addresses
* Management network
** One IPv4 address (pre-configured) for the management IP address (MIP) of each node
** One IPv4 address (free/spare/unconfigured) for the management virtual IP address (MVIP) of the cluster. This address is configured on the management network interface during Astra Data Store cluster installation.
* Cluster network
** One IPv4 address (pre-configured) for the cluster IP address of each node on the data network interface. As an alternative, the MIP of the management network interface can be used.
* Data network
One IPv4 address (free/spare/unconfigured) for the volume's export address of each node. This address is configured on the data network interface during Astra Data Store cluster installation.

//POLARIS-654 and POLARIS-450
== Persistent volume sharing requirements
Each Astra Data Store cluster supports using persistent volumes to cover the storage needs of any apps installed on that cluster. Persistent volumes in Astra Data Store have the following requirements and limitations:

.Requirements
* NFS 4.1 client/server in Kubernetes clusters
* Kubernetes apps will access files through persistent volumes shared over NFS 4.1, which requires the the AUTH_SYS authentication method.

.Capabilities
* Parallel NFS (pNFS) is not supported.
* Only IP-based export policies are supported.

//POLARIS-458
== Node minimum resource requirements
A minimum size cluster of Astra Data Store is 3 nodes. The minimum resource requirements for each node in an Astra Data Store cluster are as follows:

* Minimum number of drives: 2
* Minimum number of CPU cores: 4
* Minimum RAM: 4GB
* Minimum number of NW BW: 10Gb
* Minimum storage capacity: 1TB

//POLARIS-460
//dissimilar node types and HW and capabilities are supported for scale
== Astra Data Store cluster expansion requirements
Astra Data Store supports nodes of different types and capabilities in a cluster. If you are expanding a cluster, Astra Data Store supports adding nodes with any performance capabilities, as long as they are not lower than the least performant node in the cluster. All nodes, including new nodes during an expansion, need to at least meet the minimum requirements in <<Node physical resource requirements>>.

//POLARIS-461
== Astra Data Store storage requirements
Astra Data Store clusters support SAS and NVMe TLC SSD storage with the following capabilities:

* Maximum capacity per drive: 15.36TB
* Maximum number of drives per node: 24
* Maximum number of nodes per cluster: 40
* Each of the Kubernetes worker nodes which are part of the Astra Data Store deployment should have the same type and number of physical disks
* The drives need to be addressable as SCSI devices, and each drive must have a unique serial number

//POLARIS-656 - more questions here for HA requirements (Naveen M is SME)
== Astra Data Store high availability requirements
Astra Data Store requires Element 12.3 or later for high availability to function correctly. High availability makes use of the Element software Protection Domains feature.

//POLARIS-1285 - Do we want to document ports that ASDS uses?
== Required TCP ports
Astra Data Store requires that you open the following ports in the internal firewall configuration:

|===
|Port |Description

|Port
|Description

|Port
|Description

|Port
|Description

|Port
|Description

|Port
|Description

|Port
|Description

|Port
|Description

|===

//POLARIS-2317 and 2316
== Astra Data Store Starter Edition feature and expansion capabilities
Astra Data Store Starter Edition has certain feature and expansion limitations.

.Minimum resource requirements
Min. Memory requirement per node: 32GiB

.Feature capabilities
* NFS vVols are not supported
* Cloud connection is required

.Expansion limitations

|===
|Resource |Limits

|Number of nodes in a cluster
|5

|Persistent volumes per node
|10

|vCPU cores per node
|9

|vCPU cores per Cluster
|45

|Max. Capacity per node
|1TiB

|Max. Capacity per Cluster
|4TiB + 1TiB

|Max. Capacity per Volume
|1TiB
|===

//POLARIS-479
== Astra Data Store cluster capabilities
Astra Data Store has the following cluster capabilities:

* Maximum cluster size: 40 nodes
* Minimum volume size: 1GiB
* Maximum volume size: 100TB
* Maximum number of volumes per Astra Data Store cluster: 4000
* Maximum number of snapshots per volume: 256
* Capacity – multiple PB of usable capacity

== What's next

View the link:quick-start.html[quick start] overview.
