---
sidebar: sidebar
permalink: get-started/setup-ads.html
keywords: astra, astra data store, setup, trident, backend
summary: After you have installed Astra Data Store and addressed some environmental prerequisites, you'll install or update Astra Trident, configure K8s snapshot capabilities, set up the storage backend, and create a default storage class.
---

= Set up Astra Data Store components
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

After you have installed Astra Data Store and addressed some environmental prerequisites, you'll install or update Astra Trident, configure K8s snapshot capabilities, set up the storage backend, and create a default storage class:

* <<Install Astra Trident>>
* <<Install K8s Snapshot CRDs and Controller>>
* <<Set up Astra Data Store as storage backend>>
* <<Create a default Astra Data Store storage class>>

== Install Astra Trident

To install Trident, download the installation bundle from the NetApp Support Site and perform a series a commands to install Trident in your environment.

.What you'll need
* link:requirements.html[Before you begin installation, prepare your environment for Astra Data Store deployment].
* Root administrative permissions.
* Internet connectivity. Astra Data Store Preview does not support air-gapped environments.

.Steps
. Create and open a new Trident directory:
+
----
mkdir trident
cd trident
----

. If you are installing from an internet-connected environment, download the Trident bundle from the NetApp Support Site using a secure, file-transfer tool, such as GNU wget:
+
----
wget <https://github.com/NetApp/trident/releases/download/v21.10.0/trident-installer-21.10.0.tar.gz>
Resolving ... 10.193.34.109
Connecting to |10.193.34.109|:8081... connected.
HTTP request sent, awaiting response... 200 OK
Length: 87210186 (83M) [application/x-tgz]
Saving to: ‘trident-installer-21.10.0.tar.gz’

100%[======================================================================================================================================================================================================================================>] 87,210,186   107MB/s   in 0.8s

2021-07-01 16:31:43 (107 MB/s) - ‘trident-installer-21.10.0.tar.gz’ saved [87210186/87210186]
----

. Extract the images from the bundle:
+
Sample command and response:
+
----
gunzip trident-installer-21.10.0.tar.gz
trident_docker_image.tgz
trident-operator_docker_image.tgz
trident-installer-21.07.0-test.jenkins-trident-submit-287.tar.gz
trident-operator-21.07.0-test.jenkins-trident-submit-287.tgz
----

. Load the Trident images into your preferred registry. All images should be loaded under one parent directory path; for example,  `nexus.barnacle.company.com:5001/trident`.
+
Sample commands and responses:
+
----
[root@example trident]# docker load -i trident_docker_image.tgz
d2de0904777e: Loading layer [==================================================>] 51.69 MB/51.69 MB
c110bbf04909: Loading layer [==================================================>]  39.7 MB/39.7 MB
0f7ceb16c114: Loading layer [==================================================>] 1.248 MB/1.248 MB
Loaded image: nexus.barnacle.company.com:5001/trident:21.07.0-test.jenkins-trident-submit-287

[root@example trident]# docker images | grep trident
nexus.barnacle.netapp.com:5001/trident             21.07.0-test.jenkins-trident-submit-287   9ed44525ee10        8 days ago          94.4 MB
----

. Install Trident:
.. Extract the Trident installer:
+
----
gunzip trident-installer-21.07.0-test.jenkins-trident-submit-287.tar.gz
----

.. List the required sidecar images and their corresponding versions for the installed Kubernetes version.
// These sidecar images need to be downloaded from public repository??? A sample required trident sidecar images for k8s v1.19.0 are:
+
----
tridentctl images
----
+
Sample response:
+
----
k8s.gcr.io/sig-storage/csi-provisioner:v2.1.1
k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
k8s.gcr.io/sig-storage/csi-resizer:v1.1.0
k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0
----

.. Load sidecar images to the parent registry:
... Change to the Trident installer directory:
+
----
cd trident-installer
----

... Enter the full path for the parent registry that contains all Trident images for `[registry_full_path]`; for example, `nexus.barnacle.company.com:5001/trident`, and run the command:
//Make sure the 'k8s.gcr.io/sig-storage' path is removed from the image path while pushing them under parent path???
+
----
./tridentctl install –debug --image-registry [registry_full_path] -n trident
----
+
Sample response:
+
----
INFO Created Kubernetes clients.                   namespace=default version=v1.21.2
W0701 16:35:23.835995   27909 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0701 16:35:23.837720   27909 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0701 16:35:23.839377   27909 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0701 16:35:23.841455   27909 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0701 16:35:23.846474   27909 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0701 16:35:23.848624   27909 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0701 16:35:23.850769   27909 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0701 16:35:23.852833   27909 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0701 16:35:23.854837   27909 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0701 16:35:23.856952   27909 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0701 16:35:24.037261   27909 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
INFO Starting Trident installation.                namespace=trident
INFO Created namespace.                            namespace=trident
INFO Created service account.
INFO Created cluster role.
INFO Created cluster role binding.
W0701 16:35:24.097810   27909 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0701 16:35:24.100987   27909 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
INFO Created Trident pod security policy.
W0701 16:35:24.117681   27909 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0701 16:35:24.119927   27909 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0701 16:35:24.122045   27909 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0701 16:35:24.124118   27909 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0701 16:35:24.126166   27909 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0701 16:35:24.128214   27909 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0701 16:35:24.130436   27909 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0701 16:35:24.132501   27909 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
INFO Added finalizers to custom resource definitions.
W0701 16:35:24.157003   27909 warnings.go:70] storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 CSIDriver
W0701 16:35:24.159669   27909 warnings.go:70] storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 CSIDriver
INFO Created Trident service.
INFO Created Trident secret.
INFO Created Trident deployment.
INFO Created Trident daemonset.
INFO Waiting for Trident pod to start.
INFO Trident pod started.                          deployment=trident-csi namespace=trident pod=trident-csi-6457bdd4d4-k9rw6
INFO Waiting for Trident REST interface.
INFO Trident REST interface is up.                 version=21.07.0-test.jenkins-trident-submit-287+c201299862cc3502e8e97eea6e801577134916dc
INFO Trident installation succeeded.
----

.. Verify that Trident was successfully installed by verifying that the pods are up and running:
+
----
kubectl get pods -n trident
----
+
Sample response:
+
----
NAME                           READY   STATUS    RESTARTS   AGE
trident-csi-6457bdd4d4-k9rw6   6/6     Running   0          32s
trident-csi-6hgsr              1/2     Running   2          32s
trident-csi-8jhtx              1/2     Running   2          32s
trident-csi-nh2kq              2/2     Running   0          32s
trident-csi-sjksd              1/2     Running   2          32s
----

== Install K8s Snapshot CRDs and Controller

K8s snapshot CRDs and controller are required to create PVC snapshots. If you do not already have the CRD and controller installed for your environment, run the following commands to install them.

NOTE: The following command examples assume `/Trident` as the directory; however, the directory you use can be any directory that you used to download the YAML files.

.What you'll need
* link:requirements.html[Before you begin installation, prepare your environment for Astra Data Store deployment].
* Download the link:https://github.com/kubernetes-csi/external-snapshotter/tree/master/deploy/kubernetes/snapshot-controller[Kubernetes snapshot controller YAML files]:
** k8s-setup-snapshot-controller.yaml
** k8s-rbac-snapshot-controller.yaml
* Download the link:https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd[YAML CRDs]:
** snapshot.storage.k8s.io_volumesnapshotclasses.yaml
** snapshot.storage.k8s.io_volumesnapshotcontents.yaml
** snapshot.storage.k8s.io_volumesnapshots.yaml

.Steps
. Apply snapshot.storage.k8s.io_volumesnapshotclasses.yaml:
+
----
kubectl apply -f trident/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
----
+
Response:
+
----
customresourcedefinition.apiextensions.k8s.io/volumesnapshotclasses.snapshot.storage.k8s.io created
----

. Apply snapshot.storage.k8s.io_volumesnapshotcontents.yaml:
+
----
kubectl apply -f trident/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
----
+
Response:
+
----
customresourcedefinition.apiextensions.k8s.io/volumesnapshotcontents.snapshot.storage.k8s.io created
----

. Apply snapshot.storage.k8s.io_volumesnapshots.yaml:
+
----
kubectl apply -f trident/snapshot.storage.k8s.io_volumesnapshots.yaml
----
+
Response:
+
----
customresourcedefinition.apiextensions.k8s.io/volumesnapshots.snapshot.storage.k8s.io created
----

. Apply k8s-setup-snapshot-controller.yaml:
+
----
kubectl apply -f trident/k8s-setup-snapshot-controller.yaml
----
+
Response:
+
----
deployment.apps/snapshot-controller created
----

. Apply k8s-setup-snapshot-controller.yaml:
+
----
kubectl apply -f trident/k8s-rbac-snapshot-controller.yaml
----
+
Response:
+
----
serviceaccount/snapshot-controller created
clusterrole.rbac.authorization.k8s.io/snapshot-controller-runner created
clusterrolebinding.rbac.authorization.k8s.io/snapshot-controller-role created
role.rbac.authorization.k8s.io/snapshot-controller-leaderelection created
rolebinding.rbac.authorization.k8s.io/snapshot-controller-leaderelection created
----

. Verify that the CRD YAML files are applied:
+
----
k get crd | grep volumesnapshot
----
+
Sample response:
+
----
astradsvolumesnapshots.astrads.netapp.io              2021-08-04T17:48:21Z
volumesnapshotclasses.snapshot.storage.k8s.io         2021-08-04T22:05:49Z
volumesnapshotcontents.snapshot.storage.k8s.io        2021-08-04T22:05:59Z
volumesnapshots.snapshot.storage.k8s.io               2021-08-04T22:06:17Z
----

. Verify that the snapshot controller files are applied:
+
----
k get pods -n kube-system | grep snapshot
----
+
Sample response:
+
----
snapshot-controller-7f58886ff4-cdh78                                    1/1     Running   0          13s
snapshot-controller-7f58886ff4-tmrd9                                    1/1     Running   0          32s
----

== Set up Astra Data Store as storage backend

Configure storage backend parameters in the ads_backend.json file and create the Astra Data Store storage backend.

.Steps
. Open `ads_backend.json` in a secure terminal:
+
----
cat ads_backend.json
----
. Configure the JSON file:
.. Change the `"cluster"` value to the cluster name for the Astra Data Store cluster.
.. Change the `"namespace"` value to the namespace you want to use with volume creation.
.. Change the `"autoExportPolicy"` value to `true` unless you set up an exportpolicy CR instead for this backend.
.. Populate the `"autoExportCIDRs"` list with IP addresses you want to grant access. Use `0.0.0.0/0` to allow all.
//"kubeconfig" → Convert .kube/config yaml file to json without spaces(minimize), then base64 it and use the base64 output
//python3 -c 'import sys, yaml, json; json.dump(yaml.load(sys.stdin), sys.stdout, indent=None)' < kubeconfig_filepath > kubeconf.json
//cat kubeconf.json | base64 | tr -d '\n'
//. "defaults" → List of defaults:
//snapshotPolicy,
//exportPolicy,
//snapshotDir,
//qosPolicy,
//size
+
[subs=+quotes]
----
{
    "version": 1,
    "storageDriverName": "astrads-nas",
    "storagePrefix": "",
    *"cluster": "example-1234584",*
    *"namespace": "astrads-system",*
    *"autoExportPolicy": true,*
    *"autoExportCIDRs": ["0.0.0.0/0"],*
    "kubeconfig": "<ID>",
    "debugTraceFlags": {"method": true, "api": true},
    "labels": {"cloud": "on-prem", "creator": "trident-dev"},
    "defaults": {
        "qosPolicy": "bronze"
    },
    "storage": [
        {
            "labels": {
                "performance": "extreme"
            },
            "defaults": {
                "qosPolicy": "bronze"
            }
        },
        {
            "labels": {
                "performance": "premium"
            },
            "defaults": {
                "qosPolicy": "bronze",
            }
        },
        {
            "labels": {
                "performance": "standard"
            },
            "defaults": {
                "qosPolicy": "bronze"
            }
        }
    ]
}
----

. Create the storage backend:
+
----
tridentctl create backend -f ads_backend.json -n trident
----
+
Sample response:
+
----
+------------------+----------------+--------------------------------------+--------+---------+
|       NAME       | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+------------------+----------------+--------------------------------------+--------+---------+
| example-1234584 | astrads-nas    | 2125fa7a-730e-43c8-873b-6012fcc3b527 | online |       0 |
+------------------+----------------+--------------------------------------+--------+---------+
----

== Create a default Astra Data Store storage class

Create the Trident default storage class and apply it to the storage backend.

.Steps
. Create the trident-csi storage class:
.. Run the following command:
+
----
cat ads_sc_generic.yaml
----
+
Response:
+
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: trident-csi
provisioner: csi.trident.netapp.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - vers=4
----

.. Create trident-csi:
+
----
kubectl create -f ads_sc_generic.yaml
----
+
Response:
+
----
storageclass.storage.k8s.io/trident-csi created
----

. Verify that the storage class has been added:
+
----
kubectl get storageclass -A
----
+
Response:
+
----
NAME          PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
trident-csi   csi.trident.netapp.io   Delete          Immediate           true                   6h29m
----

. Verify that the Trident backend has been updated with the default storage class parameters:
+
----
tridentctl get backend -n trident -o yaml
----
+
Sample response:
+
[subs=+quotes]
----
items:
- backendUUID: 2125fa7a-730e-43c8-873b-6012fcc3b527
  config:
    autoExportCIDRs:
    - 0.0.0.0/0
    autoExportPolicy: true
    backendName: ""
    cluster: example-1234584
    credentials: null
    debug: false
    debugTraceFlags:
      api: true
      method: true
    defaults:
      exportPolicy: default
      qosPolicy: bronze
      size: 1G
      snapshotDir: "false"
      snapshotPolicy: none
    disableDelete: false
    kubeconfig: <ID>
    labels:
      cloud: on-prem
      creator: trident-dev
    limitVolumeSize: ""
    namespace: astrads-system
    nfsMountOptions: ""
    region: ""
    serialNumbers: null
    storage:
    - defaults:
        exportPolicy: ""
        qosPolicy: bronze
        size: ""
        snapshotDir: ""
        snapshotPolicy: ""
      labels:
        performance: extreme
      region: ""
      supportedTopologies: null
      zone: ""
    - defaults:
        exportPolicy: ""
        qosPolicy: bronze
        size: ""
        snapshotDir: ""
        snapshotPolicy: ""
      labels:
        performance: premium
      region: ""
      supportedTopologies: null
      zone: ""
    - defaults:
        exportPolicy: ""
        qosPolicy: bronze
        size: ""
        snapshotDir: ""
        snapshotPolicy: ""
      labels:
        performance: standard
      region: ""
      supportedTopologies: null
      zone: ""
    storageDriverName: astrads-nas
    storagePrefix: ""
    supportedTopologies: null
    version: 1
    zone: ""
  configRef: ""
  name: example-1234584
  online: true
  protocol: file
  state: online
  storage:
    example-1234584_pool_0:
      name: example-1234584_pool_0
      storageAttributes:
        backendType:
          offer:
          - astrads-nas
        clones:
          offer: true
        encryption:
          offer: false
        labels:
          offer:
            cloud: on-prem
            creator: trident-dev
            performance: extreme
        snapshots:
          offer: true
      storageClasses:
      - trident-csi
      supportedTopologies: null
    example-1234584_pool_1:
      name: example-1234584_pool_1
      storageAttributes:
        backendType:
          offer:
          - astrads-nas
        clones:
          offer: true
        encryption:
          offer: false
        labels:
          offer:
            cloud: on-prem
            creator: trident-dev
            performance: premium
        snapshots:
          offer: true
      storageClasses:
      - trident-csi
      supportedTopologies: null
    example-1234584_pool_2:
      name: example-1234584_pool_2
      storageAttributes:
        backendType:
          offer:
          - astrads-nas
        clones:
          offer: true
        encryption:
          offer: false
        labels:
          offer:
            cloud: on-prem
            creator: trident-dev
            performance: standard
        snapshots:
          offer: true
      storageClasses:
      *- trident-csi*
      supportedTopologies: null
  volumes: []
----
