---
sidebar: sidebar
permalink: release-notes/known-limitations.html
keywords: astra, control center, limitations, known limitations, interoperability
summary: Known limitations identify platforms, devices, or functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.
---

= Known limitations with this release
:hardbreaks:
:icons: font
:imagesdir: ../media/release-notes/

Known limitations identify platforms, devices, or functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.

== Functionality to remove one or more nodes is not supported
Although Astra Data Store does not support node removal functionality, it does support failed node removal.

== Functionality to remove one or more drives is not supported
Although Astra Data Store does not support drive removal functionality, it does support the functionality to replace failed drives.

== Add drive functionality is not supported
Astra Data Store does not support the functionality to add drives.

== Firewall-enabled configuration is not supported
Astra Data Store does not support firewall-enabled configurations.

== Upgrade functionality is not provided in this release
The functionality to upgrade Astra Data Store will be provided in a future release.

== Autosupport periodic settings cannot be disabled in this release
//CB review
In the preview release, the periodic settings that are used for sending mandatory telemetry Autosupport bundles should not be changed. If you disable the sending of periodic Autosupport bundles, the cluster will be locked down and new volumes cannot be created until periodic settings are enabled again.
 
== Find more information

* link:../release-notes/known-issues.html[Known issues for this release]
