---
sidebar: sidebar
permalink: release-notes/known-issues.html
keywords: astra, control center, bugs, known issues, problems
summary: Known issues identify problems that might prevent you from using this release of the product successfully.
---

= Known issues
:hardbreaks:
:icons: font
:imagesdir: ../media/release-notes/

Known issues identify problems that might prevent you from using this preview release of the product successfully.

== Default Calico WireGuard interface name is not recognized by Astra Data Store preview
//burt 1442348
This error causes the pods to crash. As a workaround, change the wireguardInterfaceName setting in Calico’s Felix configuration to specify an interface name without a dot. For example:

----
calicoctl patch felixconfiguration default --type='merge' -p '{"spec":{"wireguardInterfaceName":"calico_wg"}}'
----

In addition to creating interfaces on each node with the new name, this change might also leave behind the original wireguard.cali interfaces. Delete these interfaces to prevent this issue from recurring.

== MongoDB deployment with default liveness probe value fails with pods in crash loop
As a workaround, set the liveness probe initialDelaySeconds to 600 seconds in the MongoDB deployment spec.

== Find more information

* link:../release-notes/known-limitations.html[Known limitations]
