---
sidebar: sidebar
permalink: release-notes/known-issues.html
keywords: astra, control center, bugs, known issues, problems
summary: Known issues identify problems that might prevent you from using this release of the product successfully.
---

= Known issues with this release
:hardbreaks:
:icons: font
:imagesdir: ../media/release-notes/

Known issues identify problems that might prevent you from using this release of the product successfully.

== Operator fails to select nodes when optional AdsNodeCount field is not set in cluster CR
//???
As a workaround, link:../get-started/install-ads.html#install-the-astra-data-store-cluster[specify the node count value] in the `AdsNodeCount` field in the astradscluster.yaml custom resource (CR).

== Calico Encryption interface name format conflict causes FireTap to crash
//burt 1442348
When Calico WireGuard Encryption is enabled, the default behavior is to create an interface named wireguard.cali on each node. This name format (the use of a dot) causes FireTap to crash during startup.

To correct, change the wireguardInterfaceName setting in Calico's Felix configuration to specify an interface name without a dot. Here is one example of the many ways to modify the setting:

----
calicoctl patch felixconfiguration default --type='merge' -p '{"spec":{"wireguardInterfaceName":"calico_wg"}}'
----

In addition to creating interfaces on each node with the new name, this change might also leave behind the original wireguard.cali interfaces. Delete these interfaces to prevent this issue from recurring.

== Find more information

* link:../release-notes/known-limitations.html[Known limitations for this release]
