---
sidebar: sidebar
permalink: release-notes/known-limitations.html
keywords: astra, astra data store, control center, limitations, known limitations, interoperability
summary: Known limitations identify platforms, devices, or functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.
---

= Known limitations
:hardbreaks:
:icons: font
:imagesdir: ../media/release-notes/

Known limitations identify platforms, devices, or functions that are not supported by this Early Access Program (EAP) release of the product or do not interoperate correctly with it.

== Astra Data Store 22.05 Early Access Program (EAP) release
This release includes these known limitations. Review these known limitations carefully.

=== All IP addresses must be known to interfaces
Astra Data Store requires that there are no unknown IP addresses configured on a worker node in the same subnet as the Data IP or Cluster IP. The presence of an unknown address will cause cluster creation to fail. An unknown IP address is any address that is not configured on the management interface, cluster interface, or storage interface.

=== Astra Data Store deployed with Cilium CNI requires portmap chaining
An Astra Data Store deployed with Cilium CNI requires the portmap plugin for HostPort support.

For K8s environments using Cilium in eBPF mode, you can enable portmap chaining mode by adding `cni-chaining-mode: portmap` to the `cilium-config` configMap and restarting Cilium pods.

=== VMware integrations limitations
The following workflows are not supported in this release:

* VM: Clone, suspend, and snapshot with memory
* Snapshot and revert of a VM with multiple disks
* vVol replication

The following functionality is not supported:

* First Class Disks (FCDs)
* VMware vMotion
* Compliance alerts and notifications
* Multi-vCenter and multi-VASA Provider configurations are not supported. A single VASA Provider per vCenter configuration is supported.
* NFSv4.1 is not supported.
* For all services, only a single instance of a pod is supported.
* Storage policy-based management is applicable only at the VM level and cannot be modified after VM creation.

== Find more information

* link:../release-notes/known-issues.html[Known issues]
