---
sidebar: sidebar
permalink: release-notes/known-issues.html
keywords: astra, control center, bugs, known issues, problems
summary: Known issues identify problems that might prevent you from using this release of the product successfully.
---

= Known issues
:hardbreaks:
:icons: font
:imagesdir: ../media/release-notes/

Known issues identify problems that might prevent you from using this release of the product successfully.

== Astra Data Store 22.04 release
This release includes these known issues. Review these known issues carefully.

=== Astra Data Store uninstallation process might cause pods to remain in a terminating state
The Astra Data Store preview uninstall process in Kubernetes v1.20 can occasionally cause pods to remain in a terminating state.

See link:../use/uninstall-ads-manual.html[Uninstall Astra Data Store preview manually without a script] or
link:../use/uninstall-ads.html[Uninstall Astra Data Store preview automatically with a script].


== Find more information

* link:../release-notes/known-limitations.html[Known limitations]
